const meta = {
  '01_linguistics-basics': '01. 국어학 기초 지도: 음운·형태·통사·의미·화용 개관',
  '02_literature-basics': '02. 문학 일반 이론과 갈래·용어 지도',
  '03_korean-literary-history-map': '03. 한국 문학사 시대 구분과 큰 흐름',
  '04_literary-theory-map': '04. 문학비평·문학이론 지도: 주요 이론 한눈에 보기',
  '05_phonology-deep': '05. 국어 음운론 심화: 음운 체계와 음운 변동',
  '06_morphology-deep': '06. 형태론 심화: 품사 체계와 단어 형성',
  '07_syntax-semantics-pragmatics': '07. 통사론·의미론·화용론 기초와 출제 포인트',
  '08_norms-and-orthography': '08. 국어 규범·문자·표기·방언 개관',
  '09_history-of-korean-language': '09. 국어사: 시대별 국어의 변천과 특징',
  '10_classical-poetry-genres': '10. 고전 시가 갈래 체계: 상고가요~조선시대 시가',
  '11_classical-poetry-interpretation': '11. 고전 시가 작품 해석과 기출 유형',
  '12_classical-prose-and-hanmun': '12. 고전 산문·한문학·구비문학',
  '13_classical-authors-and-history': '13. 고전문학 주요 작가·작품·문학사 흐름',
  '14_modern-poetry-history': '14. 현대시 문학사와 사조: 개화기~현대',
  '15_modern-poetry-analysis': '15. 현대시 작품 분석: 이미지·상징·화자·구조',
  '16_modern-novel-narrative': '16. 현대소설 서사 구조와 인물·시점 분석',
  '17_modern-novel-history': '17. 현대소설 문학사와 주요 작가·작품',
  '18_drama-and-essay': '18. 현대 희곡·수필·기타 갈래',
  '19_literary-criticism-theories': '19. 문학비평 이론: 형식주의·구조주의·정신분석 등',
  '20_korean-literary-criticism': '20. 한국 문학비평의 흐름과 대표 비평가',
  '21_mixed-type-practice-sets': '21. 출제기준 전 범위 혼합 유형 모의세트',
  '22_korean-linguistics-past-questions': '22. 국어학 영역 기출·예상 문제',
  '23_classical-literature-past-questions': '23. 고전문학 영역 기출·예상 문제',
  '24_modern-literature-past-questions': '24. 현대문학 영역 기출·예상 문제',
  '25_full-mock-finals': '25. 독학사 4단계 국어 최종 모의고사',
}

export default meta
