const meta = {
  '01_linux-architecture-and-distribution': '01. 리눅스 구조와 배포판',
  '02_filesystem-hierarchy': '02. 파일 시스템 계층과 경로',
  '03_basic-commands-and-file-operations': '03. 기본 명령어와 파일 조작',
  '04_text-search-and-redirection': '04. 텍스트 확인, 검색과 리다이렉션',
  '05_permissions-and-umask': '05. 권한, 소유자와 umask',
  '06_users-groups-and-pam': '06. 사용자, 그룹과 PAM',
  '07_package-management': '07. 패키지 관리와 소스 설치',
  '08_process-job-and-signal': '08. 프로세스, 작업과 시그널',
  '09_systemd-service-and-log': '09. systemd 서비스와 로그',
  '10_disk-partition-filesystem-and-mount': '10. 디스크, 파티션, 파일 시스템과 마운트',
  '11_lvm-and-raid': '11. LVM과 RAID',
  '12_ip-subnet-and-routing': '12. IP 주소, 서브넷과 라우팅',
  '13_network-diagnostic-commands': '13. 네트워크 진단 명령어',
  '14_ssh-and-remote-management': '14. SSH와 원격 관리',
  '15_shell-script-basics': '15. 셸 스크립트 기초',
  '16_regex-grep-sed-awk': '16. 정규표현식, grep, sed와 awk',
  '17_kernel-module-and-hardware': '17. 커널, 모듈과 하드웨어',
  '18_boot-grub-and-recovery': '18. 부팅, GRUB와 복구',
  '19_time-cron-and-at': '19. 시간 설정, cron과 at',
  '20_web-service-and-dns': '20. 웹 서비스와 DNS',
  '21_file-sharing-mail-and-transfer': '21. 파일 공유, 메일과 전송 서비스',
  '22_firewall-and-selinux': '22. 방화벽과 SELinux',
  '23_security-hardening-and-audit': '23. 보안 강화와 감사',
  '24_backup-recovery-and-rsync': '24. 백업, 복구와 rsync',
  '25_virtualization-and-container': '25. 가상화와 컨테이너',
  '26_performance-monitoring': '26. 성능 모니터링과 자원 분석',
  '27_system-failure-diagnosis': '27. 시스템 장애 진단 시나리오',
  '28_network-security-scenarios': '28. 네트워크·보안 실전 시나리오',
  '29_first-exam-practice': '29. 1차 객관식 실전 점검',
  '30_second-exam-practice': '30. 2차 단답·서술 실전 점검',
  '31_기출-practice-round-1': '31. 1차 기출 연습 1회 — 시스템 관리',
  '32_기출-practice-round-2': '32. 1차 기출 연습 2회 — 네트워크·서비스',
  '33_기출-practice-round-3': '33. 1차 최종 실전 50문항',
  '34_practical-mock-1': '34. 2차 실기 모의 1회',
  '35_practical-mock-2': '35. 2차 실기 모의 2회',
  '36_practical-exam-checklist': '36. 2차 실기 핵심 암기 체크리스트',
}

export default meta
