const meta = {
  '01_basic-notation': '01. 이산수학에서 쓰는 기호와 표기법',
  '02_exam-overview': '02. 독학사 2단계 이산수학 시험 구조·출제기준 지도',
  '03_propositions-connectives': '03. 명제와 논리연산: 진리표부터 등가식까지',
  '04_predicates-quantifiers': '04. 술어논리와 정량자, 논리적 추론 기초',
  '05_proof-techniques': '05. 증명 기법: 직접·대우·모순·수학적 귀납법',
  '06_sets-basic': '06. 집합의 기본 개념과 연산, 부분집합·멱집합',
  '07_relations-functions-overview': '07. 관계와 함수: 정의·표현·기본 분류',
  '08_equivalence-order-relations': '08. 관계의 성질: 동치 관계와 순서 관계',
  '09_counting-basics': '09. 세기와 기본 조합론: 합·곱 원리, 순열·조합',
  '10_inclusion-exclusion': '10. 포함배제원리와 응용, 비둘기집 원리 기초',
  '11_number-theory-basics': '11. 정수론 기초: 나눗셈, 최대공약수와 합동',
  '12_sequences-recursive-def': '12. 수열과 점화관계: 정의와 단순 예제',
  '13_recurrence-solutions': '13. 선형 점화식 풀이: 특성방정식과 일반해',
  '14_graph-basics': '14. 그래프의 정의·표현과 기본 성질',
  '15_euler-hamilton-trees': '15. Euler/Hamilton 경로와 트리·스패닝 트리',
  '16_boolean-algebra': '16. 부울대수와 논리식의 단순화',
  '17_logic-circuits-basics': '17. 논리회로와 부울식: 게이트와 카르노 맵 기초',
  '18_induction-advanced': '18. 수학적 귀납법 심화와 조합·점화 응용',
  '19_integrated-proofs-counting-graphs': '19. 세기·그래프·점화가 얽힌 종합 증명·계산',
  '20_past-exam-patterns': '20. 최신 기출로 보는 출제 경향과 단원별 포인트',
  '21_practice-logic-sets-relations': '21. 논리·집합·관계·함수 종합 연습문제',
  '22_practice-counting-number-theory': '22. 세기·조합·정수론 종합 연습문제',
  '23_practice-recurrence-graphs-trees': '23. 점화식·그래프·트리 계산·증명 연습문제',
  '24_practice-boolean-circuits': '24. 부울대수·논리회로 종합 연습문제',
  '25_mock-exam-1': '25. 독학사 2단계 이산수학 예상 모의고사 ①',
  '26_mock-exam-2': '26. 독학사 2단계 이산수학 예상 모의고사 ②',
}

export default meta
