const meta = {
  '01_exam-structure': '01. 독학사 C프로그래밍 시험 구조와 출제기준 읽기',
  '02_c-syntax-basics': '02. C프로그램 구조와 기본 문법 기호 읽는 법',
  '03_types-operators-map': '03. C 자료형·연산자·키워드 용어 지도 (영문 중심)',
  '04_stdio-io-terms': '04. 표준 입출력과 시험에 자주 나오는 I/O 용어',
  '05_memory-model-overview': '05. C 메모리 모델 큰 그림 (스택·힙·정적 영역)',
  '06_program-structure': '06. C프로그램 구조와 컴파일·실행 흐름',
  '07_data-types-basics': '07. 기본 자료형과 변수 선언·초기화',
  '08_operators-expressions': '08. 연산자와 표현식 평가 순서',
  '09_control-flow': '09. 조건문·반복문 제어 구조',
  '10_functions-basics': '10. 함수 정의·호출과 매개변수 전달',
  '11_arrays-strings': '11. 배열과 문자열 기초',
  '12_pointers-basics': '12. 포인터 기초: 주소·역참조·포인터와 배열의 관계',
  '13_pointers-functions': '13. 포인터와 함수: 인자 전달·포인터 인자·배열 인자',
  '14_struct-union-enum': '14. 구조체·공용체·열거형',
  '15_preprocessor-basics': '15. 선행처리기: 매크로·조건부 컴파일·헤더',
  '16_file-io': '16. 파일 입출력 기초',
  '17_dynamic-memory': '17. 동적 메모리 할당: malloc/free와 문자열·배열',
  '18_struct-pointer-file': '18. 구조체·포인터·파일 입출력 통합',
  '19_string-library': '19. 문자열 라이브러리 함수와 시험 단골 패턴',
  '20_standard-library-overview': '20. 시험에 자주 등장하는 표준 라이브러리 함수 모음',
  '21_error-debugging': '21. 컴파일 오류·런타임 오류·논리 오류 분석 연습',
  '22_exam-english-terms': '22. 시험 지문 영문 키워드·전문용어 정리',
  '23_past-questions-1': '23. 독학사 C프로그래밍 기출·유형 ① (기본 문법·제어문)',
  '24_past-questions-2': '24. 독학사 C프로그래밍 기출·유형 ② (배열·문자열·포인터)',
  '25_past-questions-3': '25. 독학사 C프로그래밍 기출·유형 ③ (구조체·파일·동적 메모리)',
  '26_mock-exam-1': '26. 독학사 2단계 C프로그래밍 모의고사 ① (전 범위)',
  '27_mock-exam-2': '27. 독학사 2단계 C프로그래밍 모의고사 ② (난이도 강화)',
}

export default meta
