const meta = {
  '01_c-syntax-basics': '01. C프로그램 구조와 기본 문법 기호 읽는 법',
  '02_types-operators-map': '02. C 자료형·연산자·키워드 용어 지도 (영문 중심)',
  '03_stdio-io-terms': '03. 표준 입출력과 시험에 자주 나오는 I/O 용어',
  '04_memory-model-overview': '04. C 메모리 모델 큰 그림 (스택·힙·정적 영역)',
  '05_program-structure': '05. C프로그램 구조와 컴파일·실행 흐름',
  '06_data-types-basics': '06. 기본 자료형과 변수 선언·초기화',
  '07_operators-expressions': '07. 연산자와 표현식 평가 순서',
  '08_control-flow': '08. 조건문·반복문 제어 구조',
  '09_functions-basics': '09. 함수 정의·호출과 매개변수 전달',
  '10_arrays-strings': '10. 배열과 문자열 기초',
  '11_pointers-basics': '11. 포인터 기초: 주소·역참조·포인터와 배열의 관계',
  '12_pointers-functions': '12. 포인터와 함수: 인자 전달·포인터 인자·배열 인자',
  '13_struct-union-enum': '13. 구조체·공용체·열거형',
  '14_preprocessor-basics': '14. 선행처리기: 매크로·조건부 컴파일·헤더',
  '15_file-io': '15. 파일 입출력 기초',
  '16_dynamic-memory': '16. 동적 메모리 할당: malloc/free와 문자열·배열',
  '17_struct-pointer-file': '17. 구조체·포인터·파일 입출력 통합',
  '18_string-library': '18. 문자열 라이브러리 함수와 시험 단골 패턴',
  '19_standard-library-overview': '19. 시험에 자주 등장하는 표준 라이브러리 함수 모음',
  '20_error-debugging': '20. 컴파일 오류·런타임 오류·논리 오류 분석 연습',
  '21_exam-english-terms': '21. 시험 지문 영문 키워드·전문용어 정리',
  '22_past-questions-1': '22. 독학사 C프로그래밍 기출·유형 ① (기본 문법·제어문)',
  '23_past-questions-2': '23. 독학사 C프로그래밍 기출·유형 ② (배열·문자열·포인터)',
  '24_past-questions-3': '24. 독학사 C프로그래밍 기출·유형 ③ (구조체·파일·동적 메모리)',
  '25_mock-exam-1': '25. 독학사 2단계 C프로그래밍 모의고사 ① (전 범위)',
  '26_mock-exam-2': '26. 독학사 2단계 C프로그래밍 모의고사 ② (난이도 강화)',
}

export default meta
