const meta = {
  '01_exam-structure': '01. 독학사 4단계 국사 시험 구조와 출제 기준',
  '02_historical-framework': '02. 한국사 시대 구분과 전 범위 구조 재정리',
  '03_question-types': '03. 독학사 국사 유형 지도: 개념·사료·비교·함정 선지',
  '04_core-concepts-method': '04. 4단계 국사에서 요구되는 사고 방식과 학습 전략',
  '05_prehistoric-early-states': '05. 선사와 국가 형성: 사회 구조와 국가의 탄생',
  '06_three-kingdoms-unification': '06. 삼국과 통일 신라·발해: 정치 구조와 대외관계',
  '07_land-tax-ancient': '07. 고대의 토지·조세·신분 제도 비교',
  '08_goryeo-politics-society': '08. 고려의 정치 체제와 사회 구조',
  '09_goryeo-economy-culture': '09. 고려의 경제와 불교 문화·사상',
  '10_joseon-early-system': '10. 조선 전기의 건국과 통치 체제',
  '11_land-tax-joseon': '11. 조선 전·후기의 토지·조세·신분 제도 종합 비교',
  '12_neo-confucianism-ideology': '12. 성리학·사림·조선 정치 사상',
  '13_late-joseon-reforms': '13. 조선 후기 경제 변화와 사회 개혁·실학',
  '14_opening-modern-state': '14. 개항기와 대한제국: 개혁과 근대 국가 시도',
  '15_colonial-rule': '15. 일제 강점기의 통치 체제와 식민지 경제',
  '16_independence-movements': '16. 독립운동의 전개: 국내외 무장·민족운동·사회운동',
  '17_division-modern-korea': '17. 해방·분단과 대한민국 현대사: 정치·경제·사회',
  '18_thematic-comparisons': '18. 시대 횡단 비교: 토지·신분·통치·개혁 종합 정리',
  '19_thought-religion-ideology': '19. 불교·성리학·실학·동학·근대 사상의 흐름',
  '20_source-reading': '20. 사료·문헌·도표 읽기: 독학사 국사 사료형 대비',
  '21_trap-options': '21. 보기 선지 함정 패턴과 오답 소거 기술',
  '22_integrated-mock': '22. 독학사 4단계 국사 통합 모의고사',
  '23_past-paper-analysis': '23. 회차별 기출 분석: 출제 경향과 난이도',
  '24_final-drill': '24. 독학사 4단계 국사 예상기출·최종 점검 문제',
}

export default meta
