const meta = {
  '01_why-modern-html': '01. 왜 최근 몇 년 사이 HTML이 다시 바뀌었는가',
  '02_reading-baseline-and-compat': '02. Baseline과 브라우저 호환성 표 읽는 법',
  '03_dialog-modal-basics': '03. `<dialog>`로 만드는 진짜 모달',
  '04_dialog-forms-and-focus': '04. `<dialog>`의 폼 연동과 포커스 관리',
  '05_popover-basics': '05. Popover API로 만드는 가벼운 오버레이',
  '06_popover-vs-dialog': '06. Popover와 dialog, 무엇을 언제 쓰는가',
  '07_details-exclusive-accordion': '07. details name으로 만드는 아코디언',
  '08_inert-attribute': '08. inert로 서브트리 비활성화하기',
  '09_hidden-until-found': '09. hidden="until-found"와 페이지 내 검색',
  '10_search-landmark': '10. `<search>` 요소와 검색 랜드마크',
  '11_template-slot-dsd-overview': '11. `<template>`·slot·Declarative Shadow DOM 개요',
  '12_modern-input-types': '12. 폼 입력 타입, 현대적으로 다시 보기',
  '13_constraint-validation-api': '13. Constraint Validation API로 검증 제어하기',
  '14_mobile-form-affordances': '14. inputmode·enterkeyhint로 모바일 키보드 제어하기',
  '15_autocomplete-tokens': '15. autocomplete 토큰 체계 제대로 쓰기',
  '16_srcset-and-sizes': '16. srcset과 sizes로 해상도 스위칭하기',
  '17_picture-art-direction': '17. `<picture>`와 아트 디렉션',
  '18_image-loading-and-priority': '18. 이미지 로딩 전략: `loading`·`decoding`·`fetchpriority`',
  '19_video-audio-track': '19. `<video>`·`<audio>`·`<track>`로 미디어 접근성 갖추기',
  '20_resource-hints': '20. 리소스 힌트로 네트워크 미리 준비하기',
  '21_modules-and-importmap': '21. `<script type="module">`과 import map',
  '22_metadata-and-discoverability': '22. 메타데이터로 공유·설치 가능하게 만들기',
  '23_structured-data-json-ld': '23. JSON-LD 구조화 데이터와 SEO',
  '24_security-attributes': '24. 문서에 붙이는 보안 속성',
  '25_internationalization-attributes': '25. 국제화 속성: lang·dir·bdi·ruby',
  '26_customizable-select-experimental': '26. 실험적 기능: Customizable select',
  '27_build-overlay-ui-kit': '27. 종합 실습 1: 모달·팝오버·아코디언 UI 키트 만들기',
  '28_build-responsive-media-page': '28. 종합 실습 2: 반응형 이미지·비디오 로딩 전략 페이지',
  '29_build-accessible-form-and-review': '29. 종합 실습 3: 접근성 있는 폼 + 메타데이터 페이지와 완료 점검',
}

export default meta
