const meta = {
  '01_modern-css-boundary': '01. Modern CSS는 어디서부터 시작하는가',
  '02_baseline-and-feature-queries': '02. Baseline 읽는 법과 @supports',
  '03_cascade-layers': '03. 캐스케이드 레이어 @layer',
  '04_is-where-selectors': '04. :is()와 :where()로 선택자 줄이기',
  '05_has-relational-selector': '05. `:has()`로 부모·형제 선택하기',
  '06_css-nesting': '06. CSS 네이티브 중첩(nesting)',
  '07_container-queries-basics': '07. 컨테이너 쿼리 기본',
  '08_container-units-and-style-queries': '08. 컨테이너 단위와 스타일 쿼리',
  '09_scope-at-rule': '09. `@scope`로 스타일 격리하기',
  '10_subgrid': '10. 서브그리드로 정렬 맞추기',
  '11_experimental-masonry': '11. 아직 쓸 수 없는 masonry의 현재',
  '12_logical-properties': '12. 논리 속성으로 방향에 무관하게 쓰기',
  '13_custom-properties-deep-dive': '13. 커스텀 속성이 캐스케이드 안에서 움직이는 방식',
  '14_at-property': '14. @property로 커스텀 속성에 타입 주기',
  '15_new-color-spaces': '15. 새 색 공간: oklch가 바꾼 것',
  '16_color-mix-and-relative-color': '16. color-mix()와 상대 색 문법',
  '17_light-dark-and-color-scheme': '17. light-dark()와 color-scheme',
  '18_clamp-and-fluid-typography': '18. clamp()와 유동 타이포그래피',
  '19_aspect-ratio': '19. aspect-ratio로 비율 고정하기',
  '20_starting-style-and-discrete-transition': '20. @starting-style과 이산 값 전환',
  '21_view-transitions-basics': '21. 뷰 전환(View Transitions) 기본',
  '22_view-transitions-advanced': '22. 뷰 전환 심화와 페이지 간(cross-document) 전환의 현실',
  '23_scroll-driven-animations': '23. 스크롤 연동 애니메이션',
  '24_anchor-positioning': '24. 앵커 포지셔닝으로 툴팁·팝오버 배치하기',
  '25_text-wrap-and-form-sizing': '25. text-wrap, field-sizing, interpolate-size',
  '26_prefers-media-features': '26. prefers-*로 사용자 선호에 맞추기',
  '27_focus-visible-and-accent-color': '27. focus-visible과 accent-color',
  '28_modern-css-architecture': '28. 현대적 CSS 아키텍처 선택하기',
  '29_build-design-token-theme': '29. 종합 실습 1: 색 토큰과 다크모드 테마 시스템',
  '30_build-responsive-component': '30. 종합 실습 2: 컨테이너 반응형 카드와 앵커 툴팁',
  '31_build-motion-and-checklist': '31. 종합 실습 3: 전환·스크롤 애니메이션과 완료 점검',
}

export default meta
