const meta = {
  '01_dl-terminology-map': '01. 딥러닝 용어 지도: 기본 개념·기호·표기법',
  '02_ml-vs-dl': '02. 머신러닝과 딥러닝: 학습 유형과 관계',
  '03_exam-skills': '03. 독학사 딥러닝 필기 시험 전략과 계산·서술 스킬',
  '04_perceptron-mlp-basics': '04. 퍼셉트론과 다층 퍼셉트론(MLP) 기본 구조',
  '05_activation-loss': '05. 활성화 함수와 손실 함수 비교 정리',
  '06_forward-backprop': '06. 순전파와 역전파: 계산 절차와 수식',
  '07_optimizers': '07. 최적화 알고리즘: SGD, Momentum, RMSprop, Adam',
  '08_overfitting-regularization': '08. 과적합과 정규화: L1/L2·Dropout·Early Stopping',
  '09_batchnorm-data-aug': '09. 배치 정규화와 데이터 증강·초기화',
  '10_cnn-basics': '10. CNN 기본 연산: 합성곱·패딩·스트라이드·풀링',
  '11_cnn-architectures': '11. 대표 CNN 구조: LeNet·AlexNet·VGG·ResNet',
  '12_rnn-lstm-gru': '12. 순환신경망(RNN)과 LSTM·GRU',
  '13_embeddings-seq2seq': '13. 임베딩과 Seq2Seq, Attention 개요',
  '14_transformer-overview': '14. Transformer 개요: Self-Attention과 Encoder–Decoder',
  '15_autoencoder-vae': '15. 오토인코더(AE)와 변분 오토인코더(VAE)',
  '16_gan-basics': '16. GAN 기본 구조와 훈련 함정',
  '17_transfer-finetune': '17. 전이학습과 미세조정(Fine-tuning)',
  '18_metrics-evaluation': '18. 분류·회귀 평가지표: 혼동행렬·F1·ROC/AUC',
  '19_practical-tricks': '19. 딥러닝 학습 실무 요소와 독학사 스타일 응용 문제',
  '20_core-concepts-drills': '20. 핵심 개념 유형 문제 100제 (MLP·역전파·정규화)',
  '21_cnn-rnn-drills': '21. CNN·RNN·LSTM·GRU 유형 문제 80제',
  '22_attention-transformer-drills': '22. Attention·Transformer·임베딩·Seq2Seq 유형 문제',
  '23_generation-transfer-drills': '23. 생성 모델·전이학습·평가지표 유형 문제',
  '24_past-exam-1': '24. 독학사 3단계 딥러닝 기출 1회분 해설 (최근 A년도)',
  '25_past-exam-2': '25. 독학사 3단계 딥러닝 기출 1회분 해설 (최근 B년도)',
  '26_mixed-mock': '26. 독학사 3단계 딥러닝 실전 모의고사 1회분',
  '27_final-review': '27. 시험 직전 2주 완성: 핵심 압축 정리와 함정 체크리스트',
}

export default meta
