const meta = {
  '01_dl-terminology-map': '01. 딥러닝 용어 지도: 기본 개념·기호·표기법',
  '02_ml-vs-dl': '02. 머신러닝과 딥러닝: 학습 유형과 관계',
  '03_perceptron-mlp-basics': '03. 퍼셉트론과 다층 퍼셉트론(MLP) 기본 구조',
  '04_activation-loss': '04. 활성화 함수와 손실 함수 비교 정리',
  '05_forward-backprop': '05. 순전파와 역전파: 계산 절차와 수식',
  '06_optimizers': '06. 최적화 알고리즘: SGD, Momentum, RMSprop, Adam',
  '07_overfitting-regularization': '07. 과적합과 정규화: L1/L2·Dropout·Early Stopping',
  '08_batchnorm-data-aug': '08. 배치 정규화와 데이터 증강·초기화',
  '09_cnn-basics': '09. CNN 기본 연산: 합성곱·패딩·스트라이드·풀링',
  '10_cnn-architectures': '10. 대표 CNN 구조: LeNet·AlexNet·VGG·ResNet',
  '11_rnn-lstm-gru': '11. 순환신경망(RNN)과 LSTM·GRU',
  '12_embeddings-seq2seq': '12. 임베딩과 Seq2Seq, Attention 개요',
  '13_transformer-overview': '13. Transformer 개요: Self-Attention과 Encoder–Decoder',
  '14_autoencoder-vae': '14. 오토인코더(AE)와 변분 오토인코더(VAE)',
  '15_gan-basics': '15. GAN 기본 구조와 훈련 함정',
  '16_transfer-finetune': '16. 전이학습과 미세조정(Fine-tuning)',
  '17_metrics-evaluation': '17. 분류·회귀 평가지표: 혼동행렬·F1·ROC/AUC',
  '18_practical-tricks': '18. 딥러닝 학습 실무 요소와 독학사 스타일 응용 문제',
  '19_core-concepts-drills': '19. 핵심 개념 유형 문제 100제 (MLP·역전파·정규화)',
  '20_cnn-rnn-drills': '20. CNN·RNN·LSTM·GRU 유형 문제 80제',
  '21_attention-transformer-drills': '21. Attention·Transformer·임베딩·Seq2Seq 유형 문제',
  '22_generation-transfer-drills': '22. 생성 모델·전이학습·평가지표 유형 문제',
  '23_past-exam-1': '23. 독학사 3단계 딥러닝 기출 1회분 해설 (최근 A년도)',
  '24_past-exam-2': '24. 독학사 3단계 딥러닝 기출 1회분 해설 (최근 B년도)',
  '25_mixed-mock': '25. 독학사 3단계 딥러닝 실전 모의고사 1회분',
  '26_final-review': '26. 딥러닝 핵심 개념 비교와 오류 진단',
}

export default meta
