const meta = {
  '01_infosec-domain-map': '01. 정보보안 5대 영역과 CIA 개념 지도',
  '02_os-account-permission-practice': '02. 리눅스·윈도우 계정·권한 실무 기초',
  '03_tcpip-protocol-stack': '03. TCP/IP 프로토콜 스택 완전 정리',
  '04_crypto-math-basics': '04. 암호수학 기초: 모듈러 연산부터 이산로그까지',
  '05_law-and-governance-map': '05. 정보보호 법령·거버넌스 체계 지도',
  '06_server-os-account-auth': '06. 서버·클라이언트 운영체제 계정·인증 실무',
  '07_filesystem-access-control': '07. 파일시스템 접근통제와 무결성 점검',
  '08_system-attack-techniques': '08. 시스템 공격기법과 대응',
  '09_server-security-ops': '09. 서버 보안 운영 실무: 로그·백업·최적화',
  '10_server-security-tools': '10. 서버 보안 S/W 설치·운영과 취약점 점검',
  '11_network-devices-services': '11. 네트워크 장비 원리와 서비스 운영 실무',
  '12_scanning-sniffing-spoofing': '12. 스캐닝·스니핑·스푸핑·원격접속 공격과 탐지',
  '13_dos-ddos-attacks': '13. DoS·DDoS 공격 심화와 최신 사례',
  '14_secure-protocols-vpn': '14. 보안 프로토콜과 VPN 실무: SSL/TLS·IPSec',
  '15_network-security-solutions': '15. 네트워크 보안 솔루션 운영과 최신 동향',
  '16_web-security-ops': '16. 웹 보안 실무 I: 웹서버 운영과 OWASP 주요 공격',
  '17_web-secure-coding': '17. 웹 보안 실무 II: 시큐어코딩과 취약점 진단',
  '18_ftp-mail-dns-security': '18. FTP·메일·DNS 서비스 보안',
  '19_db-ecommerce-security': '19. 데이터베이스 보안과 전자상거래 인증기술',
  '20_forensics-and-app-trends': '20. 디지털 포렌식 실무와 최신 애플리케이션 보안 동향',
  '21_authentication-deep': '21. 인증 기술 심화: 사용자·메시지·디바이스·생체인증',
  '22_access-control-models': '22. 접근통제 정책과 모델',
  '23_crypto-algorithms-deep': '23. 대칭키·공개키 암호 알고리즘 심화',
  '24_hash-signature-pki-ops': '24. 해시함수·전자서명·PKI 실무',
  '25_key-distribution-crypto-trends': '25. 키 분배 프로토콜과 최신 암호기술 동향',
  '26_governance-risk-assessment': '26. 정보보호 거버넌스와 위험평가 실무',
  '27_isms-p-and-controls': '27. 정보보호 대책 구현·운영과 ISMS-P 인증제도 실무',
  '28_network-law-deep': '28. 정보통신망법·정보통신기반보호법·전자서명법 심화',
  '29_privacy-law-deep': '29. 개인정보보호법 조문별 심화와 처벌 규정',
  '30_cyber-ethics-and-law-trends': '30. 사이버 윤리·금지행위와 최신 법 개정 동향',
  '31_past-questions-system-network': '31. 기출·예상문제: 시스템보안·네트워크보안',
  '32_past-questions-application': '32. 기출·예상문제: 애플리케이션보안',
  '33_past-questions-general-security': '33. 기출·예상문제: 정보보안일반(암호·인증·접근통제)',
  '34_past-questions-mgmt-law': '34. 기출·예상문제: 정보보안관리 및 법규',
  '35_mock-exam-full': '35. 정보보안기사 필기 통합 모의고사',
}

export default meta
