const meta = {
  '01_sql-and-database-basics': '01. SQL과 관계형 데이터베이스 기초',
  '02_notation-and-terms-map': '02. ERD 표기법과 용어 지도',
  '03_entity-attribute-relationship': '03. 엔터티, 속성, 관계의 정의',
  '04_identifiers-candidate-primary-alternate': '04. 식별자: 후보키, 기본키, 대체키, 복합키',
  '05_erd-notation-and-reading': '05. ERD 읽고 그리기: 실전 표기 연습',
  '06_normalization-1nf-to-3nf': '06. 정규화 1: 1NF~3NF',
  '07_normalization-bcnf-and-denormalization': '07. 정규화 2: BCNF와 반정규화',
  '08_relationship-and-join-concept': '08. 관계와 조인의 개념적 연결',
  '09_transaction-and-null': '09. 트랜잭션 개념과 NULL 속성',
  '10_ddl-and-constraints': '10. DDL과 제약조건',
  '11_dml-insert-update-delete-merge': '11. DML: INSERT, UPDATE, DELETE, MERGE',
  '12_tcl-and-transaction-control': '12. TCL: COMMIT, ROLLBACK, SAVEPOINT',
  '13_where-and-operators': '13. WHERE 절과 연산자',
  '14_single-row-functions': '14. 단일행 함수: 문자·숫자·날짜·변환',
  '15_group-functions-and-groupby-having': '15. 그룹 함수와 GROUP BY/HAVING',
  '16_standard-joins': '16. 표준 조인: INNER, OUTER, CROSS, SELF',
  '17_subqueries': '17. 서브쿼리: 단일행, 다중행, 상관',
  '18_set-operators': '18. 집합 연산자: UNION, UNION ALL, INTERSECT, MINUS',
  '19_window-functions-rank-family': '19. 윈도우 함수 1: RANK, DENSE_RANK, ROW_NUMBER',
  '20_window-functions-aggregate-and-frame': '20. 윈도우 함수 2: 집계 함수와 프레임(ROWS/RANGE)',
  '21_grouping-sets-rollup-cube': '21. GROUPING SETS, ROLLUP, CUBE',
  '22_top-n-and-hierarchical-query': '22. Top N 쿼리와 계층형 질의',
  '23_pivot-and-misc': '23. PIVOT과 기타 활용 구문',
  '24_dcl-and-procedural-sql-intro': '24. DCL과 절차형 SQL 개요',
  '25_dbms-syntax-differences': '25. DBMS별 문법 차이: Oracle vs MySQL vs 표준 SQL',
  '26_mock-exam-1': '26. SQLD 예상 모의고사 1회',
  '27_mock-exam-2': '27. SQLD 예상 모의고사 2회',
  '28_mock-exam-3': '28. SQLD 예상 모의고사 3회',
  '29_mock-exam-4': '29. SQLD 예상 모의고사 4회',
  '30_mock-exam-5': '30. SQLD 예상 모의고사 5회',
}

export default meta
