const meta = {
  '01_relational-database-and-table': '01. 관계형 데이터베이스와 테이블',
  '02_data-modeling-and-erd': '02. 데이터 모델링과 ERD',
  '03_entity-and-attribute': '03. 엔터티, 속성, 도메인',
  '04_relationship-and-cardinality': '04. 관계, 차수, 선택성',
  '05_identifier-and-key': '05. 식별자와 키',
  '06_normalization': '06. 정규화',
  '07_model-and-sql': '07. 데이터 모델과 SQL',
  '08_select-and-alias': '08. SELECT, DISTINCT, 별칭',
  '09_data-types-and-null': '09. 자료형과 NULL',
  '10_where-and-conditions': '10. WHERE와 조건식',
  '11_functions': '11. SQL 함수',
  '12_group-by-and-having': '12. GROUP BY와 HAVING',
  '13_order-by-and-case': '13. ORDER BY와 CASE',
  '14_join-basics': '14. 조인 기초',
  '15_standard-joins': '15. 표준 조인과 외부 조인',
  '16_dml': '16. DML 데이터 조작',
  '17_ddl-and-dcl': '17. DDL, DCL과 제약조건',
  '18_tcl-and-transaction': '18. TCL과 트랜잭션',
  '19_subquery-and-set-operator': '19. 서브쿼리와 집합 연산자',
  '20_group-function-and-window-function': '20. 그룹 함수와 윈도우 함수',
  '21_top-n-hierarchical-and-pivot': '21. Top N, 계층형 질의와 PIVOT',
  '22_data-modeling-question-types': '22. 데이터 모델링 기출 유형',
  '23_sql-basic-question-types': '23. SQL 기본 기출 유형',
  '24_sql-utilization-question-types': '24. SQL 활용 기출 유형',
  '25_mock-exam-1': '25. 실전 모의 1회',
  '26_mock-exam-2': '26. 실전 모의 2회',
}

export default meta
