const meta = {
  '01_database-overview': '01. 데이터베이스 개요',
  '01_database-overview-review': '01-복습. 데이터베이스 개요',
  '02_database-characteristics': '02. 데이터베이스의 특징',
  '02_database-characteristics-review': '02-복습. 데이터베이스의 특징',
  '03_data-modeling-overview': '03. 데이터 모델링의 이해',
  '03_data-modeling-overview-review': '03-복습. 데이터 모델링의 이해',
  '04_data-model-overview': '04. 데이터 모델의 이해',
  '04_data-model-overview-review': '04-복습. 데이터 모델의 이해',
  '05_entity': '05. 엔터티',
  '05_entity-review': '05-복습. 엔터티',
  '06_attribute': '06. 속성',
  '06_attribute-review': '06-복습. 속성',
  '07_relationship': '07. 관계',
  '07_relationship-review': '07-복습. 관계',
  '08_identifier': '08. 식별자',
  '08_identifier-review': '08-복습. 식별자',
  '09_normalization': '09. 정규화',
  '09_normalization-review': '09-복습. 정규화',
  '10_relationship-and-join': '10. 관계와 조인의 이해',
  '10_relationship-and-join-review': '10-복습. 관계와 조인의 이해',
  '11_model-transactions': '11. 모델이 표현하는 트랜잭션의 이해',
  '11_model-transactions-review': '11-복습. 모델이 표현하는 트랜잭션의 이해',
  '12_null-attributes': '12. NULL 속성의 이해',
  '12_null-attributes-review': '12-복습. NULL 속성의 이해',
  '13_natural-and-surrogate-identifiers': '13. 본질식별자와 인조식별자',
  '13_natural-and-surrogate-identifiers-review': '13-복습. 본질식별자와 인조식별자',
  '14_relational-database-overview': '14. 관계형 데이터베이스 개요',
  '14_relational-database-overview-review': '14-복습. 관계형 데이터베이스 개요',
  '15_select-statement': '15. SELECT 문',
  '15_select-statement-review': '15-복습. SELECT 문',
  '16_sql-functions': '16. 함수',
  '16_sql-functions-review': '16-복습. 함수',
  '17_where-clause': '17. WHERE 절',
  '17_where-clause-review': '17-복습. WHERE 절',
  '18_group-by': '18. GROUP BY 절',
  '18_group-by-review': '18-복습. GROUP BY 절',
  '19_having-clause': '19. HAVING 절',
  '19_having-clause-review': '19-복습. HAVING 절',
  '20_order-by': '20. ORDER BY 절',
  '20_order-by-review': '20-복습. ORDER BY 절',
  '21_joins': '21. 조인',
  '21_joins-review': '21-복습. 조인',
  '22_standard-joins': '22. 표준 조인',
  '22_standard-joins-review': '22-복습. 표준 조인',
  '23_subqueries': '23. 서브쿼리',
  '23_subqueries-review': '23-복습. 서브쿼리',
  '24_set-operators': '24. 집합 연산자',
  '24_set-operators-review': '24-복습. 집합 연산자',
  '25_grouping-functions': '25. 그룹 함수',
  '25_grouping-functions-review': '25-복습. 그룹 함수',
  '26_window-functions': '26. 윈도우 함수',
  '26_window-functions-review': '26-복습. 윈도우 함수',
  '27_top-n-queries': '27. Top N 쿼리',
  '27_top-n-queries-review': '27-복습. Top N 쿼리',
  '28_hierarchical-queries': '28. 계층형 질의',
  '28_hierarchical-queries-review': '28-복습. 계층형 질의',
  '29_self-join': '29. 셀프 조인',
  '29_self-join-review': '29-복습. 셀프 조인',
  '30_pivot': '30. PIVOT 절',
  '30_pivot-review': '30-복습. PIVOT 절',
  '31_unpivot': '31. UNPIVOT 절',
  '31_unpivot-review': '31-복습. UNPIVOT 절',
  '32_regular-expressions': '32. 정규 표현식',
  '32_regular-expressions-review': '32-복습. 정규 표현식',
  '33_ddl': '33. DDL',
  '33_ddl-review': '33-복습. DDL',
  '34_dml': '34. DML',
  '34_dml-review': '34-복습. DML',
  '35_tcl': '35. TCL',
  '35_tcl-review': '35-복습. TCL',
  '36_dcl': '36. DCL',
  '36_dcl-review': '36-복습. DCL',
  '37_management-statements': '37. 관리 구문',
  '37_management-statements-review': '37-복습. 관리 구문',
  '38_sql-basics-summary': '38. SQL 기본',
  '38_sql-basics-summary-review': '38-복습. SQL 기본',
  '39_sql-advanced-summary': '39. SQL 활용',
  '39_sql-advanced-summary-review': '39-복습. SQL 활용',
  '40_data-model-and-performance': '40. 데이터 모델과 성능',
  '40_data-model-and-performance-review': '40-복습. 데이터 모델과 성능',
  '41_normalization-and-performance': '41. 정규화와 성능',
  '41_normalization-and-performance-review': '41-복습. 정규화와 성능',
  '42_denormalization-and-performance': '42. 반정규화와 성능',
  '42_denormalization-and-performance-review': '42-복습. 반정규화와 성능',
  '43_large-data-performance': '43. 대용량 데이터에 따른 성능',
  '43_large-data-performance-review': '43-복습. 대용량 데이터에 따른 성능',
  '44_database-structure-and-performance': '44. DB 구조와 성능',
  '44_database-structure-and-performance-review': '44-복습. DB 구조와 성능',
  '45_distributed-database-performance': '45. 분산 DB에 따른 성능',
  '45_distributed-database-performance-review': '45-복습. 분산 DB에 따른 성능',
  '46_optimizer-and-execution-plan': '46. 옵티마이저와 실행계획',
  '46_optimizer-and-execution-plan-review': '46-복습. 옵티마이저와 실행계획',
  '47_index-basics': '47. 인덱스 기본',
  '47_index-basics-review': '47-복습. 인덱스 기본',
  '48_join-mechanisms': '48. 조인 수행 원리',
  '48_join-mechanisms-review': '48-복습. 조인 수행 원리',
}

export default meta
