const meta = {
  '01_exam-overview': '01. 독학사 4단계 데이터베이스 시험 구조와 학습 전략',
  '02_syllabus-map': '02. 최신 출제기준·평가영역 읽기와 범위 지도 그리기',
  '03_db-basics-ansi-sparc': '03. 데이터베이스 시스템 개요와 ANSI/SPARC 3단계 스키마',
  '04_er-notation-primer': '04. ER/EER 다이어그램 표기법 기초',
  '05_math-logic-for-db': '05. 관계대수·관계해석을 위한 집합·논리 기초',
  '06_relational-model-keys': '06. 관계 데이터 모델과 키·무결성 제약',
  '07_relational-algebra-core': '07. 관계대수 기본 연산과 시험형 연습',
  '08_relational-algebra-advanced': '08. 관계대수 확장 연산·중첩 질의·집합 연산',
  '09_relational-calculus': '09. 관계해석(튜플·도메인)과 안전한 질의',
  '10_er-eer-modeling': '10. ER/EER 모델링과 개념적 설계',
  '11_er-to-relational': '11. ER/EER → 관계 스키마 사상 규칙',
  '12_sql-ddl-dml-basics': '12. SQL 기본: DDL·DML·제약과 단일 테이블 질의',
  '13_sql-joins-subqueries-sets': '13. SQL 중급: 조인·중첩 질의·집합 연산',
  '14_sql-grouping-views-dcl': '14. SQL 고급: 그룹화·뷰·권한과 간단한 DCL',
  '15_fd-and-anomalies': '15. 함수적 종속과 이상 현상 이해하기',
  '16_normal-forms-1nf-3nf-bcnf': '16. 정규화 I: 1NF~3NF·BCNF와 분해 절차',
  '17_normal-forms-4nf-5nf': '17. 정규화 II: 다중값·조인 종속과 4NF·5NF',
  '18_storage-and-indexing': '18. 저장 구조·파일 조직·인덱스(B-트리·B+트리·해싱)',
  '19_query-processing-optimization': '19. 질의 처리·최적화 개요',
  '20_transactions-acid': '20. 트랜잭션 개념과 ACID·직렬성',
  '21_concurrency-control': '21. 동시성 제어: 잠금·2PL·타임스탬프·교착',
  '22_recovery-and-logging': '22. 회복: 로그·체크포인트·WAL',
  '23_security-distributed-object-db': '23. 보안·권한과 분산·객체관계/객체지향 데이터베이스',
  '24_db-mixed-practice-1': '24. 독학사형 종합 연습 ① 관계모델·관계대수·기본 SQL',
  '25_db-mixed-practice-2': '25. 독학사형 종합 연습 ② 정규화·ER 사상·고급 SQL',
  '26_db-mixed-practice-3': '26. 독학사형 종합 연습 ③ 트랜잭션·동시성·회복·기타',
}

export default meta
