const meta = {
  '01_db-basics-ansi-sparc': '01. 데이터베이스 시스템 개요와 ANSI/SPARC 3단계 스키마',
  '02_er-notation-primer': '02. ER/EER 다이어그램 표기법 기초',
  '03_math-logic-for-db': '03. 관계대수·관계해석을 위한 집합·논리 기초',
  '04_relational-model-keys': '04. 관계 데이터 모델과 키·무결성 제약',
  '05_relational-algebra-core': '05. 관계대수 기본 연산과 시험형 연습',
  '06_relational-algebra-advanced': '06. 관계대수 확장 연산·중첩 질의·집합 연산',
  '07_relational-calculus': '07. 관계해석(튜플·도메인)과 안전한 질의',
  '08_er-eer-modeling': '08. ER/EER 모델링과 개념적 설계',
  '09_er-to-relational': '09. ER/EER → 관계 스키마 사상 규칙',
  '10_sql-ddl-dml-basics': '10. SQL 기본: DDL·DML·제약과 단일 테이블 질의',
  '11_sql-joins-subqueries-sets': '11. SQL 중급: 조인·중첩 질의·집합 연산',
  '12_sql-grouping-views-dcl': '12. SQL 고급: 그룹화·뷰·권한과 간단한 DCL',
  '13_fd-and-anomalies': '13. 함수적 종속과 이상 현상 이해하기',
  '14_normal-forms-1nf-3nf-bcnf': '14. 정규화 I: 1NF~3NF·BCNF와 분해 절차',
  '15_normal-forms-4nf-5nf': '15. 정규화 II: 다중값·조인 종속과 4NF·5NF',
  '16_storage-and-indexing': '16. 저장 구조·파일 조직·인덱스(B-트리·B+트리·해싱)',
  '17_query-processing-optimization': '17. 질의 처리·최적화 개요',
  '18_transactions-acid': '18. 트랜잭션 개념과 ACID·직렬성',
  '19_concurrency-control': '19. 동시성 제어: 잠금·2PL·타임스탬프·교착',
  '20_recovery-and-logging': '20. 회복: 로그·체크포인트·WAL',
  '21_security-distributed-object-db': '21. 보안·권한과 분산·객체관계/객체지향 데이터베이스',
  '22_db-mixed-practice-1': '22. 독학사형 종합 연습 ① 관계모델·관계대수·기본 SQL',
  '23_db-mixed-practice-2': '23. 독학사형 종합 연습 ② 정규화·ER 사상·고급 SQL',
  '24_db-mixed-practice-3': '24. 독학사형 종합 연습 ③ 트랜잭션·동시성·회복·기타',
}

export default meta
