const meta = {
  '01_core-terms': '01. 정보보호 핵심 용어 지도 (자산·위험·통제·취약점·위협)',
  '02_math-basics': '02. 암호학을 위한 최소 수학·논리 기초',
  '03_os-security-model': '03. 운영체제·계정·권한 개념 정리 (정보보호 관점 사전지식)',
  '04_crypto-basics': '04. 암호 시스템 개요와 대칭키 암호',
  '05_public-key-and-signature': '05. 공개키 암호·전자서명·키교환',
  '06_hash-mac': '06. 해시 함수·MAC·무결성 보호',
  '07_pki-and-protocols': '07. PKI·인증서·보안 프로토콜(TLS·IPsec 개론)',
  '08_app-db-security': '08. 애플리케이션·웹·DB 보안 기본 구조',
  '09_malware-concepts': '09. 악성코드 개념·분류·전파 방식',
  '10_vulnerabilities-web': '10. 소프트웨어·웹 취약점 유형과 공격 기법 개요',
  '11_db-access-control': '11. 데이터베이스 접근통제와 권한관리',
  '12_info-security-mgmt': '12. 정보보호 관리체계(ISMS)와 정책·조직',
  '13_access-control-and-auth': '13. 접근통제·인증·권한관리 메커니즘',
  '14_privacy-and-isms-p': '14. 개인정보보호와 ISMS-P 인증기준',
  '15_digital-forensics': '15. 디지털 포렌식 기초 개념',
  '16_network-security-basics': '16. 네트워크 보안 기본 개념과 장비',
  '17_incident-response': '17. 침해사고 대응·복구·보안관제 개요',
  '18_risk-analysis': '18. 위험분석·평가·대응 전략',
  '19_secure-dev-and-ops': '19. 안전한 시스템 도입·개발·운영',
  '20_past-questions-crypto': '20. 기출·예상문제: 암호·키관리·PKI',
  '21_past-questions-access-privacy': '21. 기출·예상문제: 접근통제·인증·개인정보보호·법령',
  '22_past-questions-systems-network': '22. 기출·예상문제: 시스템·네트워크·관리체계·위험분석',
  '23_past-questions-incident-forensics': '23. 기출·예상문제: 악성코드·침해사고·보안관제·포렌식',
}

export default meta
