const meta = {
  '01_exam-structure': '01. 독학사 3단계 정보보호 시험 구조와 출제기준 읽기',
  '02_core-terms': '02. 정보보호 핵심 용어 지도 (자산·위험·통제·취약점·위협)',
  '03_math-basics': '03. 암호학을 위한 최소 수학·논리 기초',
  '04_os-security-model': '04. 운영체제·계정·권한 개념 정리 (정보보호 관점 사전지식)',
  '05_crypto-basics': '05. 암호 시스템 개요와 대칭키 암호',
  '06_public-key-and-signature': '06. 공개키 암호·전자서명·키교환',
  '07_hash-mac': '07. 해시 함수·MAC·무결성 보호',
  '08_pki-and-protocols': '08. PKI·인증서·보안 프로토콜(TLS·IPsec 개론)',
  '09_app-db-security': '09. 애플리케이션·웹·DB 보안 기본 구조',
  '10_malware-concepts': '10. 악성코드 개념·분류·전파 방식',
  '11_vulnerabilities-web': '11. 소프트웨어·웹 취약점 유형과 공격 기법 개요',
  '12_db-access-control': '12. 데이터베이스 접근통제와 권한관리',
  '13_info-security-mgmt': '13. 정보보호 관리체계(ISMS)와 정책·조직',
  '14_access-control-and-auth': '14. 접근통제·인증·권한관리 메커니즘',
  '15_privacy-and-isms-p': '15. 개인정보보호와 ISMS-P 인증기준',
  '16_digital-forensics': '16. 디지털 포렌식 기초 개념',
  '17_network-security-basics': '17. 네트워크 보안 기본 개념과 장비',
  '18_incident-response': '18. 침해사고 대응·복구·보안관제 개요',
  '19_risk-analysis': '19. 위험분석·평가·대응 전략',
  '20_secure-dev-and-ops': '20. 안전한 시스템 도입·개발·운영',
  '21_past-questions-crypto': '21. 기출·예상문제: 암호·키관리·PKI',
  '22_past-questions-access-privacy': '22. 기출·예상문제: 접근통제·인증·개인정보보호·법령',
  '23_past-questions-systems-network': '23. 기출·예상문제: 시스템·네트워크·관리체계·위험분석',
  '24_past-questions-incident-forensics': '24. 기출·예상문제: 악성코드·침해사고·보안관제·포렌식',
}

export default meta
