const meta = {
  '01_grammar-map': '01. 독학사 영어 문법 지도: 무엇을 얼마나 알아야 하는가',
  '02_reading-basics': '02. 독학사 영어 독해 기본기: 문장·문단·지문 읽는 법',
  '03_vocab-strategy': '03. 독학사 영어 어휘·숙어 학습 전략',
  '04_life-english-overview': '04. 독학사 생활영어·의사소통 표현 개관',
  '05_parts-of-speech': '05. 품사 총정리: 명사·대명사·형용사·부사·전치사',
  '06_verb-tense': '06. 시제·동사의 기본 체계',
  '07_auxiliary-modal': '07. 조동사·조동사 구문의 함정',
  '08_active-passive': '08. 수동태: 형태·의미·출제 함정',
  '09_conditionals': '09. 가정법: 시제와 의미를 동시에 잡기',
  '10_relatives': '10. 관계사: 관계대명사·관계부사·제한·비제한',
  '11_conjunctions': '11. 접속사·접속부사·절·구 구조',
  '12_comparison': '12. 비교급·최상급·비교 구조 함정 정리',
  '13_agreement-inversion': '13. 수·시제 일치와 도치·부정어 도치',
  '14_others-grammar': '14. 기타 핵심 문법: 준동사·관용구·어법 총정리',
  '15_vocab-core': '15. 독학사 영어 핵심 어휘·숙어 ①: 품사·파생·구동사',
  '16_vocab-context': '16. 독학사 영어 핵심 어휘·숙어 ②: 동의어·문맥 어휘',
  '17_life-english-patterns': '17. 생활영어 필수 패턴: 인사·감사·사과·요청',
  '18_life-english-dialogue': '18. 생활영어 대화문 유형: 제안·동의·거절·감정 표현',
  '19_short-reading': '19. 단문 독해 유형: 문장·단락에서 답 찾기',
  '20_long-reading': '20. 장문 독해 유형: 주제·구성·논리 흐름 파악',
  '21_reading-blank-order': '21. 독해 빈칸·순서·일치·추론 문제 공략',
  '22_grammar-error-correct': '22. 어법·오류 찾기·영작형 객관식 유형',
  '23_mixed-practice': '23. 영역 통합 연습: 어휘·문법·독해·생활영어 혼합',
  '24_previous-exam-1': '24. 독학사 1단계 영어 기출 분석 ①: 최신 1회분',
  '25_previous-exam-2': '25. 독학사 1단계 영어 기출 분석 ②: 최신 2회분 비교',
  '26_previous-exam-3': '26. 독학사 1단계 영어 기출 분석 ③: 과거 경향과 변화',
  '27_mock-exam': '27. 독학사 1단계 영어 예상기출·모의고사',
}

export default meta
