const meta = {
  '01_exam-structure': '01. 독학사 1단계 영어 시험 구조와 출제기준',
  '02_grammar-map': '02. 독학사 영어 문법 지도: 무엇을 얼마나 알아야 하는가',
  '03_reading-basics': '03. 독학사 영어 독해 기본기: 문장·문단·지문 읽는 법',
  '04_vocab-strategy': '04. 독학사 영어 어휘·숙어 학습 전략',
  '05_life-english-overview': '05. 독학사 생활영어·의사소통 표현 개관',
  '06_parts-of-speech': '06. 품사 총정리: 명사·대명사·형용사·부사·전치사',
  '07_verb-tense': '07. 시제·동사의 기본 체계',
  '08_auxiliary-modal': '08. 조동사·조동사 구문의 함정',
  '09_active-passive': '09. 수동태: 형태·의미·출제 함정',
  '10_conditionals': '10. 가정법: 시제와 의미를 동시에 잡기',
  '11_relatives': '11. 관계사: 관계대명사·관계부사·제한·비제한',
  '12_conjunctions': '12. 접속사·접속부사·절·구 구조',
  '13_comparison': '13. 비교급·최상급·비교 구조 함정 정리',
  '14_agreement-inversion': '14. 수·시제 일치와 도치·부정어 도치',
  '15_others-grammar': '15. 기타 핵심 문법: 준동사·관용구·어법 총정리',
  '16_vocab-core': '16. 독학사 영어 핵심 어휘·숙어 ①: 품사·파생·구동사',
  '17_vocab-context': '17. 독학사 영어 핵심 어휘·숙어 ②: 동의어·문맥 어휘',
  '18_life-english-patterns': '18. 생활영어 필수 패턴: 인사·감사·사과·요청',
  '19_life-english-dialogue': '19. 생활영어 대화문 유형: 제안·동의·거절·감정 표현',
  '20_short-reading': '20. 단문 독해 유형: 문장·단락에서 답 찾기',
  '21_long-reading': '21. 장문 독해 유형: 주제·구성·논리 흐름 파악',
  '22_reading-blank-order': '22. 독해 빈칸·순서·일치·추론 문제 공략',
  '23_grammar-error-correct': '23. 어법·오류 찾기·영작형 객관식 유형',
  '24_mixed-practice': '24. 영역 통합 연습: 어휘·문법·독해·생활영어 혼합',
  '25_previous-exam-1': '25. 독학사 1단계 영어 기출 분석 ①: 최신 1회분',
  '26_previous-exam-2': '26. 독학사 1단계 영어 기출 분석 ②: 최신 2회분 비교',
  '27_previous-exam-3': '27. 독학사 1단계 영어 기출 분석 ③: 과거 경향과 변화',
  '28_mock-exam': '28. 독학사 1단계 영어 예상기출·모의고사',
}

export default meta
