const meta = {
  '01_numbers-and-fractions': '01. 수와 분수, 소수, 퍼센트',
  '02_data-tables-and-graphs': '02. 표와 그래프 읽기',
  '03_sigma-notation': '03. 시그마(Σ) 표기법',
  '04_functions-and-coordinates': '04. 함수와 좌표 기초',
  '05_population-sample-and-data-types': '05. 모집단, 표본과 자료의 종류',
  '06_frequency-tables-and-graphs': '06. 도수분포표와 그래프',
  '07_measures-of-center': '07. 평균, 중앙값, 최빈값',
  '08_spread-and-variability': '08. 범위, 분산, 표준편차',
  '09_relative-position': '09. 백분위수, Z점수, 사분위수',
  '10_probability-basics': '10. 표본공간, 사건, 확률 법칙',
  '11_conditional-probability': '11. 조건부확률과 독립',
  '12_bayes-theorem': '12. 베이즈 정리와 전확률 공식',
  '13_random-variables': '13. 확률변수, 기댓값, 분산',
  '14_discrete-distributions-binomial': '14. 이항분포',
  '15_discrete-distributions-poisson': '15. 포아송분포와 초기하분포',
  '16_normal-distribution': '16. 정규분포와 표준정규분포',
  '17_other-distributions': '17. t분포, F분포, 카이제곱분포',
  '18_sampling-distributions': '18. 표본평균의 분포와 중심극한정리',
  '19_point-estimation': '19. 점추정 — 불편성, 일치성, 유효성',
  '20_interval-estimation': '20. 신뢰구간',
  '21_hypothesis-testing-basics': '21. 가설, 유의수준, p값, 1종·2종 오류',
  '22_mean-proportion-tests': '22. 평균과 비율 검정',
  '23_two-sample-tests': '23. 두 집단 비교 검정',
  '24_anova-one-way': '24. 일원배치 분산분석',
  '25_anova-two-way': '25. 이원배치 분산분석',
  '26_chi-square-test': '26. 카이제곱 검정 (독립성·적합도)',
  '27_correlation': '27. 상관관계와 상관계수',
  '28_simple-regression': '28. 단순회귀분석',
  '29_statistics-question-types-1': '29. 예상기출문제 1 — 기술통계·확률',
  '30_statistics-question-types-2': '30. 예상기출문제 2 — 분포·추정·검정',
  '31_mock-exam': '31. 실전 모의고사',
}

export default meta
