const meta = {
  '01_basic-notation': '01. 이산수학에서 쓰는 기호와 표기법',
  '02_propositions-connectives': '02. 명제와 논리연산: 진리표부터 등가식까지',
  '03_predicates-quantifiers': '03. 술어논리와 정량자, 논리적 추론 기초',
  '04_proof-techniques': '04. 증명 기법: 직접·대우·모순·수학적 귀납법',
  '05_sets-basic': '05. 집합의 기본 개념과 연산, 부분집합·멱집합',
  '06_relations-functions-overview': '06. 관계와 함수: 정의·표현·기본 분류',
  '07_equivalence-order-relations': '07. 관계의 성질: 동치 관계와 순서 관계',
  '08_counting-basics': '08. 세기와 기본 조합론: 합·곱 원리, 순열·조합',
  '09_inclusion-exclusion': '09. 포함배제원리와 응용, 비둘기집 원리 기초',
  '10_number-theory-basics': '10. 정수론 기초: 나눗셈, 최대공약수와 합동',
  '11_sequences-recursive-def': '11. 수열과 점화관계: 정의와 단순 예제',
  '12_recurrence-solutions': '12. 선형 점화식 풀이: 특성방정식과 일반해',
  '13_graph-basics': '13. 그래프의 정의·표현과 기본 성질',
  '14_euler-hamilton-trees': '14. Euler/Hamilton 경로와 트리·스패닝 트리',
  '15_boolean-algebra': '15. 부울대수와 논리식의 단순화',
  '16_logic-circuits-basics': '16. 논리회로와 부울식: 게이트와 카르노 맵 기초',
  '17_induction-advanced': '17. 수학적 귀납법 심화와 조합·점화 응용',
  '18_integrated-proofs-counting-graphs': '18. 세기·그래프·점화가 얽힌 종합 증명·계산',
  '19_past-exam-patterns': '19. 최신 기출로 보는 출제 경향과 단원별 포인트',
  '20_practice-logic-sets-relations': '20. 논리·집합·관계·함수 종합 연습문제',
  '21_practice-counting-number-theory': '21. 세기·조합·정수론 종합 연습문제',
  '22_practice-recurrence-graphs-trees': '22. 점화식·그래프·트리 계산·증명 연습문제',
  '23_practice-boolean-circuits': '23. 부울대수·논리회로 종합 연습문제',
  '24_mock-exam-1': '24. 독학사 2단계 이산수학 예상 모의고사 ①',
  '25_mock-exam-2': '25. 독학사 2단계 이산수학 예상 모의고사 ②',
}

export default meta
