const meta = {
  '01_binary-and-hex': '01. 이진수·16진수 변환 — IP·MAC 주소 표기의 기초',
  '02_network-hardware-basics': '02. 네트워크 하드웨어 기초 — NIC, 케이블, 허브, 스위치, 라우터',
  '03_protocol-and-standard': '03. 프로토콜과 표준 — 통신 규약, 표준화 기관, 참조모델',
  '04_network-overview': '04. 네트워크 개요 — 정의, 분류, 성능 평가, 교환 방식',
  '05_osi-and-tcp-ip': '05. OSI 7계층·TCP/IP 참조모델',
  '06_physical-layer': '06. 물리 계층 — 신호 변환, 인코딩, 전송 매체',
  '07_data-link-layer': '07. 데이터 링크 계층 — 프레임, 오류검출, 흐름제어, ARQ',
  '08_lan-and-ethernet': '08. LAN과 이더넷 — MAC 주소, CSMA/CD, 스위치',
  '09_network-layer-ip': '09. 네트워크 계층·IP — IP 주소, 서브넷팅, CIDR',
  '10_ip-support-protocols': '10. IP 지원 프로토콜 — ARP, ICMP, IGMP, NAT',
  '11_routing': '11. 라우팅 — 정적·동적 라우팅, RIP·OSPF·BGP',
  '12_transport-layer': '12. 전송 계층 — 포트, TCP vs UDP, 3-way handshake',
  '13_application-layer': '13. 응용 계층 — DNS, HTTP·HTTPS, FTP, 이메일, DHCP',
  '14_network-security': '14. 네트워크 보안 — 암호화, 디지털서명, SSL/TLS, 방화벽·VPN',
  '15_osi-and-data-link-question-types': '15. OSI·데이터 링크 기출 유형',
  '16_ip-and-routing-question-types': '16. IP·라우팅 기출 유형',
  '17_tcp-and-app-question-types': '17. TCP·응용 계층 기출 유형',
  '18_exam-practice': '18. 컴퓨터네트워크 종합 모의고사',
}
export default meta
