const meta = {
  '01_what-are-web-apis': '01. Web API란 무엇일까?',
  '02_dom-tree-basics': '02. DOM 트리란 무엇인가',
  '03_window-and-bom': '03. window와 브라우저 객체 모델(BOM)',
  '04_dom-selection-and-traversal': '04. DOM 선택과 탐색',
  '05_dom-manipulation': '05. DOM 조작',
  '06_mutation-observer': '06. MutationObserver',
  '07_event-system': '07. 이벤트 시스템',
  '08_event-types': '08. 이벤트 종류',
  '09_form-validation': '09. 폼과 유효성 검사',
  '10_fetch-and-ajax': '10. Fetch API',
  '11_cors-and-network': '11. CORS와 네트워크 심화',
  '12_websocket': '12. WebSocket — 실시간 통신',
  '13_web-storage': '13. Web Storage와 쿠키',
  '14_history-and-url': '14. History API와 URL',
  '15_timer-and-animation': '15. 타이머와 애니메이션',
  '16_intersection-and-resize-observer': '16. Intersection·Resize Observer',
  '17_clipboard-and-drag-drop': '17. Clipboard와 Drag and Drop',
  '18_geolocation-and-media': '18. Geolocation과 미디어 API',
  '19_canvas': '19. Canvas 2D',
  '20_web-workers-and-service-workers': '20. Web Workers와 Service Workers',
  '21_webapis-practice-1': '21. Web API 핵심 퀴즈 1',
  '22_webapis-practice-2': '22. Web API 핵심 퀴즈 2',
}

export default meta
