const meta = {
  '01_ml-basics': '01. 인공지능·머신러닝·딥러닝 개념 지도',
  '02_data-and-prob': '02. 데이터·확률·통계 용어 정리',
  '03_linear-algebra-ml': '03. 머신러닝에서 쓰이는 기초 선형대수',
  '04_python-ml-tools': '04. 파이썬·scikit-learn 기본 사용법',
  '05_ml-workflow': '05. 머신러닝 전체 흐름과 데이터 전처리 개요',
  '06_learning-paradigms': '06. 지도·비지도·강화학습 패러다임',
  '07_regression-linear': '07. 선형·다항 회귀의 원리와 해석',
  '08_regression-regularization': '08. 릿지·라쏘 회귀와 정규화',
  '09_logistic-classification': '09. 로지스틱 회귀와 이진·다중 분류',
  '10_trees-and-nb': '10. 결정트리와 나이브 베이즈 분류',
  '11_knn-and-svm': '11. K-NN과 SVM: 거리 기반·마진 기반 분류',
  '12_ensemble-methods': '12. 배깅·랜덤포레스트·부스팅 개요',
  '13_unsupervised-clustering': '13. K-means·계층적 군집·DBSCAN 개념',
  '14_association-rules': '14. 연관 규칙과 항목집합 개요',
  '15_dimensionality': '15. 차원 저주의 직관과 축소 동기',
  '16_pca-lda': '16. PCA와 LDA의 개념·수식 의미',
  '17_evaluation-metrics': '17. 분류 평가 지표와 혼동행렬 계산',
  '18_model-selection': '18. 과적합·편향-분산·교차검증',
  '19_neural-basics': '19. 퍼셉트론·MLP·역전파의 역할',
  '20_practice-concepts': '20. 개념 확인·용어 정의 연습문제',
  '21_practice-calculation': '21. 계산·지표·수식 문제 집중 연습',
  '22_practice-comparison': '22. 알고리즘 비교·장단점·적용 상황 문제',
  '23_ml-mock-exam': '23. 독학사 2단계 머신러닝 예상기출모의고사',
}

export default meta
