const meta = {
  '01_practical-overview': '01. 정보처리기사 실기 시험 개요',
  '02_sw-lifecycle': '02. 소프트웨어 생명주기와 개발방법론',
  '03_requirements': '03. 요구사항 분석과 UML',
  '04_design-patterns': '04. 설계 패턴과 아키텍처',
  '05_database-sql': '05. SQL 작성과 데이터베이스 설계',
  '06_normalization': '06. 정규화와 이상현상',
  '07_algorithms': '07. 알고리즘과 자료구조',
  '08_programming-c': '08. C 언어 프로그래밍',
  '09_programming-java': '09. Java 프로그래밍',
  '10_programming-python': '10. Python 프로그래밍',
  '11_network-protocol': '11. 네트워크 프로토콜과 OSI 계층',
  '12_security': '12. 정보 보안 핵심 개념',
  '13_sw-testing': '13. 소프트웨어 테스트',
  '14_sw-quality': '14. 소프트웨어 품질과 표준',
  '15_os-concepts': '15. 운영체제 핵심 개념',
  '16_project-management': '16. 프로젝트 관리와 비용 산정',
  '17_sw-architecture': '17. 소프트웨어 아키텍처와 설계 원칙',
  '18_interface-design': '18. 인터페이스 설계와 구현',
  '19_integrated-practice-1': '19. 통합 예상 기출 1회',
  '20_integrated-practice-2': '20. 통합 예상 기출 2회',
  '21_short-answer-drill': '21. 단답형 집중 훈련',
  '22_exam-strategy': '22. 시험 전략과 핵심 암기',
}
export default meta
