const meta = {
  '00_practice-environment': '00. 부록: 실습 환경 만들기 (Docker + Rocky Linux)',
  '01_linux-and-licenses': '01. 리눅스란 무엇인가와 오픈소스 라이선스',
  '02_distributions-and-selection': '02. 배포판의 종류와 선택 기준',
  '03_installation-and-partition': '03. 리눅스 설치와 파티션 설계',
  '04_boot-process-and-runlevel': '04. 부팅 과정과 실행 레벨',
  '05_login-and-shell-basics': '05. 로그인과 셸의 기본 개념',
  '06_basic-commands-file-dir': '06. 기본 명령어 1: 파일과 디렉터리 다루기',
  '07_basic-commands-text-and-search': '07. 기본 명령어 2: 텍스트 보기와 검색',
  '08_filesystem-structure-fhs': '08. 파일시스템 구조와 디렉터리별 용도',
  '09_filesystem-commands-and-mount': '09. 파일시스템 관련 명령어와 마운트',
  '10_permissions-and-ownership': '10. 권한과 소유권',
  '11_users-and-groups': '11. 사용자와 그룹 관리',
  '12_process-concepts': '12. 프로세스의 개념',
  '13_process-commands-and-signals': '13. 프로세스 관리 명령어와 시그널',
  '14_editor-vi': '14. 에디터: vi 완전 정복',
  '15_editors-and-comparison': '15. 그 밖의 에디터와 비교',
  '16_software-installation': '16. 소프트웨어 설치와 패키지 관리',
  '17_device-management': '17. 장치 설정과 주변장치',
  '18_shell-environment-and-variables': '18. 셸 환경변수와 설정 파일',
  '19_redirection-pipe-and-scripts': '19. 입출력 재지정, 파이프, 간단한 셸 스크립트',
  '20_job-scheduling-cron-at': '20. 작업 예약: cron과 at',
  '21_x-window': '21. X 윈도 시스템',
  '22_network-basics-and-config': '22. 인터넷 활용 1: 네트워크 기초와 설정',
  '23_network-commands-and-services': '23. 인터넷 활용 2: 네트워크 명령어와 서비스 개념',
  '24_application-areas': '24. 응용분야와 리눅스가 쓰이는 자리',
  '25_mock-exam-1': '25. 리눅스마스터 2급 1차 예상 모의고사 1회',
  '26_mock-exam-2': '26. 리눅스마스터 2급 1차 예상 모의고사 2회',
  '27_mock-exam-3': '27. 리눅스마스터 2급 1차 예상 모의고사 3회',
  '28_mock-exam-4': '28. 리눅스마스터 2급 1차 예상 모의고사 4회',
  '29_mock-exam-5': '29. 리눅스마스터 2급 1차 예상 모의고사 5회',
}

export default meta
