const meta = {
  '01_exam-overview': '01. 리눅스마스터 2급 1차 시험 개요',
  '02_linux-and-licenses': '02. 리눅스란 무엇인가와 오픈소스 라이선스',
  '03_distributions-and-selection': '03. 배포판의 종류와 선택 기준',
  '04_installation-and-partition': '04. 리눅스 설치와 파티션 설계',
  '05_boot-process-and-runlevel': '05. 부팅 과정과 실행 레벨',
  '06_login-and-shell-basics': '06. 로그인과 셸의 기본 개념',
  '07_basic-commands-file-dir': '07. 기본 명령어 1: 파일과 디렉터리 다루기',
  '08_basic-commands-text-and-search': '08. 기본 명령어 2: 텍스트 보기와 검색',
  '09_filesystem-structure-fhs': '09. 파일시스템 구조와 디렉터리별 용도',
  '10_filesystem-commands-and-mount': '10. 파일시스템 관련 명령어와 마운트',
  '11_permissions-and-ownership': '11. 권한과 소유권',
  '12_users-and-groups': '12. 사용자와 그룹 관리',
  '13_process-concepts': '13. 프로세스의 개념',
  '14_process-commands-and-signals': '14. 프로세스 관리 명령어와 시그널',
  '15_editor-vi': '15. 에디터: vi 완전 정복',
  '16_editors-and-comparison': '16. 그 밖의 에디터와 비교',
  '17_software-installation': '17. 소프트웨어 설치와 패키지 관리',
  '18_device-management': '18. 장치 설정과 주변장치',
  '19_shell-environment-and-variables': '19. 셸 환경변수와 설정 파일',
  '20_redirection-pipe-and-scripts': '20. 입출력 재지정, 파이프, 간단한 셸 스크립트',
  '21_job-scheduling-cron-at': '21. 작업 예약: cron과 at',
  '22_x-window': '22. X 윈도 시스템',
  '23_network-basics-and-config': '23. 인터넷 활용 1: 네트워크 기초와 설정',
  '24_network-commands-and-services': '24. 인터넷 활용 2: 네트워크 명령어와 서비스 개념',
  '25_application-areas': '25. 응용분야와 리눅스가 쓰이는 자리',
  '26_mock-exam-1': '26. 리눅스마스터 2급 1차 예상 모의고사 1회',
  '27_mock-exam-2': '27. 리눅스마스터 2급 1차 예상 모의고사 2회',
  '28_mock-exam-3': '28. 리눅스마스터 2급 1차 예상 모의고사 3회',
  '29_mock-exam-4': '29. 리눅스마스터 2급 1차 예상 모의고사 4회',
  '30_mock-exam-5': '30. 리눅스마스터 2급 1차 예상 모의고사 5회',
}

export default meta
