const meta = {
  '01_what-is-css': '01. CSS는 무엇을 하는 언어인가',
  '02_applying-css-and-syntax': '02. CSS 적용 방법과 문법 읽는 법',
  '03_terms-map-and-devtools-preview': '03. 용어 지도와 개발자 도구 미리보기',
  '04_selectors-basic': '04. 기본 선택자: 타입·클래스·ID·전체·속성',
  '05_selectors-combinators': '05. 결합자로 관계 표현하기',
  '06_pseudo-classes': '06. 의사 클래스: 상태와 구조로 선택하기',
  '07_pseudo-elements': '07. 의사 요소: 없는 부분을 만들어 스타일링하기',
  '08_cascade-and-origin': '08. 캐스케이드: 여러 규칙이 충돌할 때',
  '09_specificity': '09. 명시도: 어느 선택자가 이기는가',
  '10_inheritance-and-value-processing': '10. 상속과 값이 결정되는 4단계',
  '11_box-model-basics': '11. 박스 모델: content·padding·border·margin',
  '12_margin-collapsing': '12. 마진 상쇄: 여백이 예상과 다르게 보일 때',
  '13_units-and-calc': '13. 단위와 값: 절대·상대·뷰포트, 그리고 calc()',
  '14_color-and-background': '14. 색과 배경',
  '15_typography-basics': '15. 타이포그래피 기본기',
  '16_display-and-flow': '16. display와 흐름 레이아웃',
  '17_block-formatting-context': '17. 블록 서식 맥락(BFC)이라는 미니 레이아웃',
  '18_position-property': '18. position과 containing block',
  '19_float-and-legacy-layout': '19. float의 역사적 역할과 한계',
  '20_flexbox-container': '20. Flexbox 컨테이너: 축과 정렬',
  '21_flexbox-items': '21. Flexbox 아이템: 크기와 순서',
  '22_flexbox-patterns': '22. Flexbox 실전 패턴',
  '23_grid-basics': '23. Grid 기본: 트랙과 fr 단위',
  '24_grid-placement': '24. Grid 배치: 라인 번호와 영역',
  '25_grid-vs-flexbox': '25. Grid와 Flexbox, 언제 무엇을 쓸까',
  '26_media-queries-basics': '26. 미디어 쿼리와 반응형 원칙',
  '27_transitions-and-transforms': '27. 전환(transition)과 변형(transform) 기본',
  '28_animations-basics': '28. 애니메이션: @keyframes와 animation',
  '29_overflow-and-stacking': '29. 오버플로와 스택 컨텍스트, z-index의 함정',
  '30_debugging-with-devtools': '30. DevTools로 CSS 디버깅하기',
  '31_build-responsive-card-grid': '31. 종합 실습 1: 반응형 카드 그리드 만들기',
  '32_build-landing-page-and-checklist': '32. 종합 실습 2: 랜딩 페이지 섹션과 완료 기준 점검',
}

export default meta
