export default {
  '01_solution-function-and-problem-solving': '01. solution 함수와 문제 해결 순서',
  '02_constraints-and-big-o': '02. 제한사항과 시간복잡도',
  '03_arrays-and-strings': '03. 배열과 문자열 순회',
  '04_hash-map-and-set': '04. 해시: Map과 Set',
  '05_stack-queue': '05. 스택과 큐',
  '06_sorting': '06. 정렬과 비교 함수',
  '07_brute-force': '07. 완전탐색',
  '08_prefix-sum-two-pointer-window': '08. 누적합·투 포인터·슬라이딩 윈도우',
  '09_binary-search': '09. 이분 탐색과 파라메트릭 서치',
  '10_recursion-and-backtracking': '10. 재귀와 백트래킹',
  '11_dfs-bfs-grid': '11. DFS·BFS와 격자 탐색',
  '12_tree-traversal': '12. 트리와 순회',
  '13_heap-priority-queue': '13. 힙과 우선순위 큐',
  '14_shortest-path': '14. 가중 그래프 최단 경로',
  '15_greedy': '15. 그리디 알고리즘',
  '16_dynamic-programming': '16. 동적 계획법',
  '17_union-find-topological-sort': '17. 유니온 파인드와 위상 정렬',
  '18_implementation-and-simulation': '18. 구현과 시뮬레이션',
  '19_mock-test-basic': '19. 기본 모의고사',
  '20_mock-test-intermediate': '20. 중급 모의고사',
  '21_mock-test-advanced': '21. 심화 모의고사',
}
