const meta = {
  '01_network-basics': '01. 네트워크 학습을 위한 용어와 그림 읽기',
  '02_binary-and-address-notes': '02. 이진수와 주소 표기의 기초',
  '03_osi-and-tcpip-map': '03. OSI 7계층과 TCP/IP 계층 대응 읽는 법',
  '04_network-math-basics': '04. 네트워크 계산을 위한 최소 수학',
  '05_network-overview': '05. 네트워크 개요와 성능 지표',
  '06_transmission-media': '06. 물리 계층의 전송 매체와 신호 표현',
  '07_multiplexing-and-switching': '07. 다중화와 교환 방식',
  '08_physical-layer-issues': '08. 물리 계층의 실제 문제들',
  '09_data-link-core': '09. 데이터링크 계층의 역할과 프레이밍',
  '10_mac-and-ethernet': '10. MAC 주소와 Ethernet의 기본 구조',
  '11_switching-and-lan': '11. 스위칭과 LAN 동작 원리',
  '12_network-layer-addressing': '12. 네트워크 계층과 IPv4 주소 체계',
  '13_subnetting-and-cidr': '13. 서브네팅 계산과 CIDR 실전',
  '14_routing-and-icmp': '14. ICMP와 라우팅의 기본 원리',
  '15_routing-algorithms': '15. 거리 벡터와 링크 상태 라우팅 비교',
  '16_ipv6-and-nat': '16. IPv6와 NAT',
  '17_transport-udp-tcp': '17. UDP와 TCP의 구조 비교',
  '18_tcp-connection-and-reliability': '18. TCP 연결 설정과 신뢰성 제어',
  '19_tcp-congestion-control': '19. TCP 혼잡 제어의 핵심',
  '20_application-protocols-dns-email': '20. 응용 계층의 대표 프로토콜: DNS와 이메일',
  '21_http-ftp-dhcp': '21. 웹과 파일 전송, 주소 할당 프로토콜',
  '22_lan-wan-wireless-sdn-iot': '22. LAN, WAN, 무선 LAN, SDN, IoT, 클라우드 네트워킹',
  '23_network-security-basics': '23. 네트워크 보안 기초',
  '24_mock-and-past-exam-1': '24. 독학사 컴퓨터네트워크 예상기출문제 1',
  '25_mock-and-past-exam-2': '25. 독학사 컴퓨터네트워크 예상기출문제 2',
  '26_mock-and-past-exam-3': '26. 독학사 컴퓨터네트워크 예상기출문제 3',
  '27_mock-and-past-exam-4': '27. 독학사 컴퓨터네트워크 예상기출문제 4',
}

export default meta
