const meta = {
  '01_korean-exam-overview': '01. 독학사 4단계 국어 시험 구조와 학습 전략',
  '02_linguistics-basics': '02. 국어학 기초 지도: 음운·형태·통사·의미·화용 개관',
  '03_literature-basics': '03. 문학 일반 이론과 갈래·용어 지도',
  '04_korean-literary-history-map': '04. 한국 문학사 시대 구분과 큰 흐름',
  '05_literary-theory-map': '05. 문학비평·문학이론 지도: 주요 이론 한눈에 보기',
  '06_exam-scope-and-trends': '06. 독학사 국어국문학 4단계 출제기준·범위·최근 경향',
  '07_phonology-deep': '07. 국어 음운론 심화: 음운 체계와 음운 변동',
  '08_morphology-deep': '08. 형태론 심화: 품사 체계와 단어 형성',
  '09_syntax-semantics-pragmatics': '09. 통사론·의미론·화용론 기초와 출제 포인트',
  '10_norms-and-orthography': '10. 국어 규범·문자·표기·방언 개관',
  '11_history-of-korean-language': '11. 국어사: 시대별 국어의 변천과 특징',
  '12_classical-poetry-genres': '12. 고전 시가 갈래 체계: 상고가요~조선시대 시가',
  '13_classical-poetry-interpretation': '13. 고전 시가 작품 해석과 기출 유형',
  '14_classical-prose-and-hanmun': '14. 고전 산문·한문학·구비문학',
  '15_classical-authors-and-history': '15. 고전문학 주요 작가·작품·문학사 흐름',
  '16_modern-poetry-history': '16. 현대시 문학사와 사조: 개화기~현대',
  '17_modern-poetry-analysis': '17. 현대시 작품 분석: 이미지·상징·화자·구조',
  '18_modern-novel-narrative': '18. 현대소설 서사 구조와 인물·시점 분석',
  '19_modern-novel-history': '19. 현대소설 문학사와 주요 작가·작품',
  '20_drama-and-essay': '20. 현대 희곡·수필·기타 갈래',
  '21_literary-criticism-theories': '21. 문학비평 이론: 형식주의·구조주의·정신분석 등',
  '22_korean-literary-criticism': '22. 한국 문학비평의 흐름과 대표 비평가',
  '23_mixed-type-practice-sets': '23. 출제기준 전 범위 혼합 유형 모의세트',
  '24_korean-linguistics-past-questions': '24. 국어학 영역 기출·예상 문제',
  '25_classical-literature-past-questions': '25. 고전문학 영역 기출·예상 문제',
  '26_modern-literature-past-questions': '26. 현대문학 영역 기출·예상 문제',
  '27_full-mock-finals': '27. 독학사 4단계 국어 최종 모의고사',
}

export default meta
