const meta = {
  '01_exam-overview': '01. 독학사 3단계 딥러닝 시험 구조와 출제기준 읽기',
  '02_dl-terminology-map': '02. 딥러닝 용어 지도: 기본 개념·기호·표기법',
  '03_ml-vs-dl': '03. 머신러닝과 딥러닝: 학습 유형과 관계',
  '04_exam-skills': '04. 독학사 딥러닝 필기 시험 전략과 계산·서술 스킬',
  '05_perceptron-mlp-basics': '05. 퍼셉트론과 다층 퍼셉트론(MLP) 기본 구조',
  '06_activation-loss': '06. 활성화 함수와 손실 함수 비교 정리',
  '07_forward-backprop': '07. 순전파와 역전파: 계산 절차와 수식',
  '08_optimizers': '08. 최적화 알고리즘: SGD, Momentum, RMSprop, Adam',
  '09_overfitting-regularization': '09. 과적합과 정규화: L1/L2·Dropout·Early Stopping',
  '10_batchnorm-data-aug': '10. 배치 정규화와 데이터 증강·초기화',
  '11_cnn-basics': '11. CNN 기본 연산: 합성곱·패딩·스트라이드·풀링',
  '12_cnn-architectures': '12. 대표 CNN 구조: LeNet·AlexNet·VGG·ResNet',
  '13_rnn-lstm-gru': '13. 순환신경망(RNN)과 LSTM·GRU',
  '14_embeddings-seq2seq': '14. 임베딩과 Seq2Seq, Attention 개요',
  '15_transformer-overview': '15. Transformer 개요: Self-Attention과 Encoder–Decoder',
  '16_autoencoder-vae': '16. 오토인코더(AE)와 변분 오토인코더(VAE)',
  '17_gan-basics': '17. GAN 기본 구조와 훈련 함정',
  '18_transfer-finetune': '18. 전이학습과 미세조정(Fine-tuning)',
  '19_metrics-evaluation': '19. 분류·회귀 평가지표: 혼동행렬·F1·ROC/AUC',
  '20_practical-tricks': '20. 딥러닝 학습 실무 요소와 독학사 스타일 응용 문제',
  '21_core-concepts-drills': '21. 핵심 개념 유형 문제 100제 (MLP·역전파·정규화)',
  '22_cnn-rnn-drills': '22. CNN·RNN·LSTM·GRU 유형 문제 80제',
  '23_attention-transformer-drills': '23. Attention·Transformer·임베딩·Seq2Seq 유형 문제',
  '24_generation-transfer-drills': '24. 생성 모델·전이학습·평가지표 유형 문제',
  '25_past-exam-1': '25. 독학사 3단계 딥러닝 기출 1회분 해설 (최근 A년도)',
  '26_past-exam-2': '26. 독학사 3단계 딥러닝 기출 1회분 해설 (최근 B년도)',
  '27_mixed-mock': '27. 독학사 3단계 딥러닝 실전 모의고사 1회분',
  '28_final-review': '28. 시험 직전 2주 완성: 핵심 압축 정리와 함정 체크리스트',
}

export default meta
