const meta = {
  '01_html-css-for-react': '01. HTML·CSS 기초',
  '02_js-for-react': '02. React를 위한 JavaScript',
  '03_react-overview': '03. React란?',
  '04_jsx': '04. JSX와 렌더링',
  '05_component': '05. 컴포넌트와 Props',
  '06_useState': '06. useState',
  '07_useEffect': '07. useEffect',
  '08_event-handling': '08. 이벤트 처리',
  '09_conditional-and-list': '09. 조건부·리스트 렌더링',
  '10_forms': '10. 폼 처리',
  '11_useRef': '11. useRef',
  '12_useContext': '12. useContext',
  '13_useReducer': '13. useReducer',
  '14_custom-hooks': '14. 커스텀 훅',
  '15_useMemo-useCallback': '15. useMemo·useCallback·React.memo',
  '16_component-patterns': '16. 컴포넌트 패턴',
  '17_data-fetching': '17. 데이터 패칭',
  '18_react-router': '18. React Router',
  '19_state-management': '19. 상태 관리 전략',
  '20_error-boundary': '20. Error Boundary·Suspense',
  '21_react-patterns': '21. 고급 React 패턴',
  '22_react-practice': '22. React 예상기출문제',
}
export default meta
