const meta = {
  '01_math-review': '01. 기초통계학을 위한 필수 수학 복습',
  '02_data-language': '02. 통계에서 쓰는 말과 기호 읽는 법',
  '03_data-handling-basics': '03. 자료 정리 기초: 표·그래프 읽기 연습',
  '04_descriptive-center': '04. 중심경향치: 평균·중앙값·최빈값의 의미와 계산',
  '05_descriptive-variation': '05. 산포와 표준화: 분산·표준편차·변동계수',
  '06_probability-basics': '06. 확률의 기초와 조건부확률',
  '07_bayes-independence': '07. 베이즈 정리와 독립성 이해하기',
  '08_random-variables': '08. 확률변수와 기댓값·분산',
  '09_main-distributions-1': '09. 이산형 분포: 이항분포·포아송분포',
  '10_main-distributions-2': '10. 연속형 분포: 정규분포와 표준정규표',
  '11_sampling-distributions': '11. 표본평균의 분포와 중심극한정리',
  '12_sampling-t-chi-f': '12. t·χ²·F 분포의 역할과 표본분포로서의 이해',
  '13_point-estimation': '13. 점추정: 좋은 추정량의 조건',
  '14_ci-one-mean': '14. 한 개 모평균의 신뢰구간',
  '15_ci-one-prop-var': '15. 모비율·모분산 신뢰구간',
  '16_ht-concepts': '16. 가설검정의 원리와 오류·p값',
  '17_ht-one-mean-prop': '17. 한 모집단의 평균·비율에 대한 가설검정',
  '18_two-sample-tests': '18. 두 모집단 비교: 평균·비율·분산 검정',
  '19_chi-square': '19. 카이제곱 검정: 적합도·독립성 검정',
  '20_correlation': '20. 상관분석: 단순상관계수 이해',
  '21_simple-regression': '21. 단순선형회귀: 회귀직선과 해석',
  '22_past-questions-1': '22. 기출·복원 문제로 보는 자료 정리·기술통계·확률',
  '23_past-questions-2': '23. 기출·복원 문제로 보는 추론(표본분포·추정·검정·회귀)',
}

export default meta
