const meta = {
  '01_exam-overview': '01. 독학사 기초통계학 시험 구조와 학습 전략',
  '02_math-review': '02. 기초통계학을 위한 필수 수학 복습',
  '03_data-language': '03. 통계에서 쓰는 말과 기호 읽는 법',
  '04_data-handling-basics': '04. 자료 정리 기초: 표·그래프 읽기 연습',
  '05_descriptive-center': '05. 중심경향치: 평균·중앙값·최빈값의 의미와 계산',
  '06_descriptive-variation': '06. 산포와 표준화: 분산·표준편차·변동계수',
  '07_probability-basics': '07. 확률의 기초와 조건부확률',
  '08_bayes-independence': '08. 베이즈 정리와 독립성 이해하기',
  '09_random-variables': '09. 확률변수와 기댓값·분산',
  '10_main-distributions-1': '10. 이산형 분포: 이항분포·포아송분포',
  '11_main-distributions-2': '11. 연속형 분포: 정규분포와 표준정규표',
  '12_sampling-distributions': '12. 표본평균의 분포와 중심극한정리',
  '13_sampling-t-chi-f': '13. t·χ²·F 분포의 역할과 표본분포로서의 이해',
  '14_point-estimation': '14. 점추정: 좋은 추정량의 조건',
  '15_ci-one-mean': '15. 한 개 모평균의 신뢰구간',
  '16_ci-one-prop-var': '16. 모비율·모분산 신뢰구간',
  '17_ht-concepts': '17. 가설검정의 원리와 오류·p값',
  '18_ht-one-mean-prop': '18. 한 모집단의 평균·비율에 대한 가설검정',
  '19_two-sample-tests': '19. 두 모집단 비교: 평균·비율·분산 검정',
  '20_chi-square': '20. 카이제곱 검정: 적합도·독립성 검정',
  '21_correlation': '21. 상관분석: 단순상관계수 이해',
  '22_simple-regression': '22. 단순선형회귀: 회귀직선과 해석',
  '23_past-questions-1': '23. 기출·복원 문제로 보는 자료 정리·기술통계·확률',
  '24_past-questions-2': '24. 기출·복원 문제로 보는 추론(표본분포·추정·검정·회귀)',
}

export default meta
