const meta = {
  '01_software-engineering-overview': '01. 소프트웨어 생명주기와 개발 방법론',
  '02_requirement-analysis': '02. 요구사항 분석과 UML 다이어그램',
  '03_system-design': '03. 시스템 설계 — 아키텍처와 모듈화',
  '04_uml-and-modeling': '04. UML과 모델링 다이어그램',
  '05_interface-design': '05. 인터페이스 설계와 UI/UX 원칙',
  '06_sw-design-practice': '06. 1과목 예상 기출문제 Quiz',
  '07_data-structure-algorithms': '07. 자료구조와 알고리즘',
  '08_programming-languages': '08. 프로그래밍 언어와 객체지향',
  '09_testing': '09. 소프트웨어 테스트',
  '10_version-control': '10. 버전 관리와 형상 관리',
  '11_application-packaging': '11. 애플리케이션 패키징과 배포',
  '12_sw-dev-practice': '12. 2과목 예상 기출문제 Quiz',
  '13_database-concepts': '13. 데이터베이스 개념과 ERD',
  '14_sql-dml': '14. SQL DML',
  '15_sql-ddl-dcl': '15. SQL DDL·DCL과 트랜잭션',
  '16_normalization-and-index': '16. 정규화와 인덱스, 뷰',
  '17_nosql-and-bigdata': '17. NoSQL과 빅데이터',
  '18_db-practice': '18. 3과목 예상 기출문제 Quiz',
  '19_c-language-basics': '19. C언어 기초',
  '20_python-basics': '20. 파이썬 기초',
  '21_java-basics': '21. 자바 기초',
  '22_shell-scripting': '22. 셸 스크립팅',
  '23_web-application': '23. 웹 애플리케이션 기초',
  '24_lang-practice': '24. 4과목 예상 기출문제 Quiz',
  '25_network-security': '25. 네트워크와 보안 기초',
  '26_sw-project-management': '26. 소프트웨어 프로젝트 관리',
  '27_it-service-management': '27. IT 서비스 관리',
  '28_information-security': '28. 정보보안 개념',
  '29_compliance-and-law': '29. 법규·컴플라이언스',
  '30_itsm-practice': '30. 5과목 예상 기출문제 Quiz',
  '31_final-mock-1': '31. 최종 모의고사 1회',
  '32_final-mock-2': '32. 최종 모의고사 2회',
}

export default meta
