const meta = {
  '01_java-baseline': '01. Java 기초 문법 리마인드와 코드 읽기 규칙',
  '02_oop-language': '02. 객체지향 프로그래밍 언어로서 Java 개관',
  '03_class-object-basics': '03. 클래스와 객체의 기본 구조',
  '04_constructors-this-super': '04. 생성자, this, super 깊게 파기',
  '05_encapsulation-access': '05. 캡슐화와 접근 제어',
  '06_packages-and-import': '06. 패키지와 import, 클래스 경로',
  '07_inheritance-and-overloading': '07. 상속과 메서드 오버로딩',
  '08_overriding-polymorphism': '08. 오버라이딩과 다형성, 동적 바인딩',
  '09_abstract-classes': '09. 추상 클래스와 템플릿 설계',
  '10_interfaces': '10. 인터페이스와 구현 클래스',
  '11_oop-principles-in-java': '11. 캡슐화·상속·다형성·추상화 종합 정리',
  '12_exceptions-basics': '12. 예외 처리와 예외 계층 구조',
  '13_exceptions-advanced': '13. 예외 처리 심화와 사용자 정의 예외',
  '14_collections-overview': '14. 컬렉션 프레임워크 개관',
  '15_collections-usage': '15. 컬렉션 구현체 선택과 성능·특성',
  '16_io-basics': '16. 입출력(I/O) 기초와 스트림',
  '17_threads-basics': '17. 스레드와 동시성 기초',
  '18_threads-sync': '18. 스레드 동기화와 간단한 문제 유형',
  '19_uml-basics': '19. UML 기초와 클래스 다이어그램 읽기',
  '20_mid-level-mock': '20. 중간 수준 모의문제: 클래스·상속·예외',
  '21_collection-thread-mock': '21. 모의문제: 컬렉션·스레드·I/O·UML',
  '22_past-paper-patterns': '22. 독학사 3단계 객체지향프로그래밍 기출 패턴 분석',
  '23_final-mock-exam': '23. 독학사 3단계 객체지향프로그래밍 최종 모의시험',
}

export default meta
