const meta = {
  '01_core-terminology': '01. 실용영어 시험용 핵심 용어·지시문 읽는 법',
  '02_logical-reading-basics': '02. 논리 독해를 위한 기본 사고 법칙',
  '03_grammar-basics-bridge': '03. 실용영어 시험에서 자주 나오는 문법 기초 다리',
  '04_exam-types-overview': '04. 실용영어 전체 출제 유형 지도',
  '05_vocabulary-frequency': '05. 실용 어휘·구동사·숙어 출제 포인트',
  '06_vocabulary-application': '06. 어휘·숙어 문제 유형별 풀이 전략',
  '07_grammar-tenses-voice': '07. 시제·태·수일치·조동사 핵심 어법',
  '08_grammar-clauses-connectors': '08. 접속사·관계사·절 구조와 논리',
  '09_grammar-agreement-parallel': '09. 병렬·일치·대명사·전치사 어법',
  '10_grammar-error-questions': '10. 문법·어법 오류 찾기·수정 유형',
  '11_reading-main-idea': '11. 주제·요지·제목·요약 독해',
  '12_reading-detail-inference': '12. 세부사항·추론·태도·함의 문제',
  '13_reading-blank-order-insertion': '13. 빈칸·순서·삽입·무관 문장 독해',
  '14_sentence-completion-transformation': '14. 문장 완성·전환·재배열·해석',
  '15_writing-short-composition': '15. 단문 영작·문장 구성 필수 구문',
  '16_practical-english-expressions': '16. 생활·실용·비즈니스 영어 필수 표현',
  '17_dialogue-questions': '17. 대화문·상황별 회화 문제 풀이',
  '18_integrated-mock-test-1': '18. 실용영어 영역 통합 모의고사 1회',
  '19_integrated-mock-test-2': '19. 실용영어 영역 통합 모의고사 2회',
  '20_past-papers-analysis-1': '20. 독학사 4단계 실용영어 기출·복원 분석 1 (최근 3개년)',
  '21_past-papers-analysis-2': '21. 독학사 4단계 실용영어 기출·복원 분석 2 (유형별 재구성)',
  '22_final-checklist': '22. 시험 직전 최종 점검·출제 포인트 체크리스트',
}

export default meta
