const meta = {
  '01_core-terminology': '01. 실용영어 시험용 핵심 용어·지시문 읽는 법',
  '02_logical-reading-basics': '02. 논리 독해를 위한 기본 사고 법칙',
  '03_grammar-basics-bridge': '03. 실용영어 시험에서 자주 나오는 문법 기초 다리',
  '04_vocabulary-frequency': '04. 실용 어휘·구동사·숙어 출제 포인트',
  '05_vocabulary-application': '05. 어휘·숙어 문제 유형별 풀이 전략',
  '06_grammar-tenses-voice': '06. 시제·태·수일치·조동사 핵심 어법',
  '07_grammar-clauses-connectors': '07. 접속사·관계사·절 구조와 논리',
  '08_grammar-agreement-parallel': '08. 병렬·일치·대명사·전치사 어법',
  '09_grammar-error-questions': '09. 문법·어법 오류 찾기·수정 유형',
  '10_reading-main-idea': '10. 주제·요지·제목·요약 독해',
  '11_reading-detail-inference': '11. 세부사항·추론·태도·함의 문제',
  '12_reading-blank-order-insertion': '12. 빈칸·순서·삽입·무관 문장 독해',
  '13_sentence-completion-transformation': '13. 문장 완성·전환·재배열·해석',
  '14_writing-short-composition': '14. 단문 영작·문장 구성 필수 구문',
  '15_practical-english-expressions': '15. 생활·실용·비즈니스 영어 필수 표현',
  '16_dialogue-questions': '16. 대화문·상황별 회화 문제 풀이',
  '17_integrated-mock-test-1': '17. 실용영어 영역 통합 모의고사 1회',
  '18_integrated-mock-test-2': '18. 실용영어 영역 통합 모의고사 2회',
  '19_past-papers-analysis-1': '19. 독학사 4단계 실용영어 기출·복원 분석 1 (최근 3개년)',
  '20_past-papers-analysis-2': '20. 독학사 4단계 실용영어 기출·복원 분석 2 (유형별 재구성)',
  '21_final-checklist': '21. 어휘·문법·독해 종합 복습',
}

export default meta
