const meta = {
  '01_what-is-service-experience-design': '01. 서비스디자인과 경험디자인이란 무엇인가',
  '02_double-diamond-and-toolkit-map': '02. 더블 다이아몬드와 서비스디자인 프로세스 지도',
  '03_answering-with-diagrams-and-documents': '03. 필답형 실기 답안을 다이어그램과 문서로 표현하는 법',
  '04_glossary-of-service-design-terms': '04. 서비스디자인 핵심 용어 지도',
  '05_requirements-and-proposal-writing': '05. 과제 요구사항 파악과 제안서 작성',
  '06_desk-research-and-environment-scan': '06. 데스크 리서치와 환경 현황 조사',
  '07_ethnographic-observation-research': '07. 관찰조사와 에스노그라피',
  '08_interview-and-fgi-design': '08. 면접조사 설계와 FGI·심층인터뷰',
  '09_synthesis-and-affinity-diagram': '09. 리서치 자료 종합과 어피니티 다이어그램',
  '10_persona-development': '10. 페르소나 개발',
  '11_customer-journey-mapping': '11. 고객 여정 지도(Customer Journey Map)',
  '12_stakeholder-analysis-and-mapping': '12. 이해관계자 분석과 이해관계자 맵',
  '13_core-user-and-design-concept': '13. 핵심 사용자 정의와 디자인 콘셉트 도출',
  '14_ideation-workshop-facilitation': '14. 아이디어 워크숍과 퍼실리테이션',
  '15_idea-elaboration-and-evaluation': '15. 아이디어 구체화와 평가',
  '16_service-structuring-and-touchpoints': '16. 서비스 구조화와 터치포인트 설계',
  '17_prototype-planning-and-design': '17. 서비스 프로토타입 기획과 설계',
  '18_prototype-making-and-simulation': '18. 서비스 프로토타입 제작과 시뮬레이션',
  '19_scenario-and-storyboard': '19. 서비스 시나리오와 스토리보드',
  '20_service-blueprint': '20. 서비스 블루프린트',
  '21_model-documentation-and-roadmap': '21. 서비스·경험 모델 문서화와 로드맵·포트폴리오',
  '22_business-model-and-value-proposition': '22. 비즈니스 모델과 가치 제안',
  '23_usability-evaluation-and-improvement': '23. 사용성 평가와 개선 방향 수립',
  '24_wrap-up-report-and-data-archiving': '24. 완료보고서·디자인 자료화·사후관리와 지식재산권 기초',
  '25_past-questions-research-persona-journey': '25. 기출 유형으로 보는 리서치·페르소나·여정지도',
  '26_past-questions-blueprint-prototype-scenario': '26. 기출 유형으로 보는 블루프린트·프로토타입·시나리오',
  '27_past-questions-workshop-ideation-bmc': '27. 기출 유형으로 보는 워크숍·아이디에이션·비즈니스모델',
  '28_mock-exam-1': '28. 서비스경험디자인기사 실기 예상 모의고사 1회',
  '29_mock-exam-2': '29. 서비스경험디자인기사 실기 예상 모의고사 2회',
}

export default meta
