const meta = {
  '01_logic-symbols-and-venn-basics': '01. 논리 기호와 벤다이어그램 읽는 법',
  '02_arithmetic-refresher': '02. 응용수리를 위한 기초 연산 복습',
  '03_vocab-hanja-map': '03. 어휘·한자성어 지도 읽는 법',
  '04_spatial-sense-basics': '04. 공간지각을 위한 도형 감각 기초',
  '05_vocab-hanja-idiom': '05. 어휘·한자성어 문제 유형',
  '06_reading-comprehension-basic': '06. 독해 기초: 주제와 세부정보 찾기',
  '07_reading-comprehension-advanced': '07. 독해 심화: 추론과 비판적 읽기',
  '08_sentence-paragraph-order': '08. 문장·문단 배열',
  '09_verbal-logic-inference': '09. 언어논리: 강화·약화와 빈칸추론',
  '10_applied-math-equations': '10. 응용수리 I: 방정식 활용 문제',
  '11_applied-math-combinatorics': '11. 응용수리 II: 경우의 수와 확률',
  '12_data-interpretation-basic': '12. 자료해석 I: 표와 그래프 읽기',
  '13_data-interpretation-advanced': '13. 자료해석 II: 복합자료와 추세 판단',
  '14_number-letter-sequence': '14. 수추리·문자추리',
  '15_propositional-logic': '15. 명제와 삼단논법',
  '16_venn-set-reasoning': '16. 벤다이어그램과 집합추리',
  '17_conditional-reasoning': '17. 조건추리: 배치와 순서',
  '18_figure-pattern-reasoning': '18. 도형·규칙추리',
  '19_unfolded-net': '19. 전개도: 입체 접고 펼치기',
  '20_block-rotation-counting': '20. 블록·큐브: 개수 세기와 회전',
  '21_cross-section-mirror-image': '21. 단면도와 거울상',
  '22_situational-judgment': '22. 상황판단: 업무 상황에서 우선순위 정하기',
  '23_organization-management-basics': '23. 조직이해: 조직도와 경영 기초 개념',
  '24_resource-management': '24. 자원관리: 시간·예산·인적·물적자원 계산',
  '25_info-tech-literacy': '25. 정보능력·기술능력: 표·코드·매뉴얼 해석',
  '26_mock-set-ncs': '26. NCS형 통합 모의세트',
  '27_mock-set-corporate-aptitude': '27. 대기업 인적성형 통합 모의세트',
  '28_mock-set-mixed-advanced': '28. 고난도 혼합 모의세트',
}

export default meta
