const meta = {
  '01_system-terminology-map': '01. 통합컴퓨터시스템 핵심 용어 지도',
  '02_math-and-performance-basics': '02. 성능·계산 문제를 위한 기본 수학 도구',
  '03_os-and-architecture-review': '03. 컴퓨터구조·운영체제 3단계 수준 빠른 복습',
  '04_computer-system-view': '04. 통합컴퓨터시스템: 전체 구조와 관점',
  '05_processor-and-instruction-set': '05. 프로세서 구조와 명령어 집합',
  '06_pipeline-basics': '06. 파이프라인 구조와 성능 계산 1',
  '07_pipeline-hazards': '07. 파이프라인 해저드와 처리 2',
  '08_memory-hierarchy-basics': '08. 메모리 계층 구조와 캐시 기본',
  '09_cache-mapping-and-policy': '09. 캐시 매핑·쓰기 정책과 계산',
  '10_io-and-storage-architecture': '10. 입출력 시스템과 저장장치 구조',
  '11_disk-raid-and-performance': '11. 디스크 스케줄링·RAID와 성능 계산',
  '12_os-structure-and-process': '12. 운영체제 구조와 프로세스·스레드: 통합 관점에서 다시 보기',
  '13_cpu-scheduling': '13. CPU 스케줄링 통합: 다단계 큐·멀티프로세서·실시간 스케줄링',
  '14_synchronization-and-deadlock': '14. 동기화 기법 비교와 교착상태: 은행원 알고리즘·검출 알고리즘 실전',
  '15_memory-management': '15. 메모리 관리: 연속 할당·단편화·주소 바인딩 계산',
  '16_virtual-memory-and-paging': '16. 가상메모리·페이징·페이지 교체',
  '17_file-system': '17. 파일 시스템 구조와 구현 개요',
  '18_multiprocessor-and-parallel': '18. 멀티프로세서·병렬·분산 시스템 개요',
  '19_integrated-system-problems-1': '19. 통합형 문항 1: CPU·메모리·I/O 연계',
  '20_integrated-system-problems-2': '20. 통합형 문항 2: 운영체제·동기화·분산',
  '21_chapter-wise-practice': '21. 출제기준 단원별 연습문제',
  '22_integrated-mock-1': '22. 통합 모의고사 1회분 (해설 포함)',
  '23_integrated-mock-2': '23. 통합 모의고사 2회분 및 출제 포인트 정리',
}

export default meta
