const meta = {
  '01_historical-framework': '01. 한국사 시대 구분과 전 범위 구조 재정리',
  '02_question-types': '02. 독학사 국사 유형 지도: 개념·사료·비교·함정 선지',
  '03_prehistoric-early-states': '03. 선사와 국가 형성: 사회 구조와 국가의 탄생',
  '04_three-kingdoms-unification': '04. 삼국과 통일 신라·발해: 정치 구조와 대외관계',
  '05_land-tax-ancient': '05. 고대의 토지·조세·신분 제도 비교',
  '06_goryeo-politics-society': '06. 고려의 정치 체제와 사회 구조',
  '07_goryeo-economy-culture': '07. 고려의 경제와 불교 문화·사상',
  '08_joseon-early-system': '08. 조선 전기의 건국과 통치 체제',
  '09_land-tax-joseon': '09. 조선 전·후기의 토지·조세·신분 제도 종합 비교',
  '10_neo-confucianism-ideology': '10. 성리학·사림·조선 정치 사상',
  '11_late-joseon-reforms': '11. 조선 후기 경제 변화와 사회 개혁·실학',
  '12_opening-modern-state': '12. 개항기와 대한제국: 개혁과 근대 국가 시도',
  '13_colonial-rule': '13. 일제 강점기의 통치 체제와 식민지 경제',
  '14_independence-movements': '14. 독립운동의 전개: 국내외 무장·민족운동·사회운동',
  '15_division-modern-korea': '15. 해방·분단과 대한민국 현대사: 정치·경제·사회',
  '16_thematic-comparisons': '16. 시대 횡단 비교: 토지·신분·통치·개혁 종합 정리',
  '17_thought-religion-ideology': '17. 불교·성리학·실학·동학·근대 사상의 흐름',
  '18_source-reading': '18. 사료·문헌·도표 읽기: 독학사 국사 사료형 대비',
  '19_trap-options': '19. 보기 선지 함정 패턴과 오답 소거 기술',
  '20_integrated-mock': '20. 독학사 4단계 국사 통합 모의고사',
  '21_past-paper-analysis': '21. 시대·사료 비교와 역사 개념 종합 연습',
  '22_final-drill': '22. 독학사 4단계 국사 예상기출·최종 점검 문제',
}

export default meta
