const meta = {
  '01_historical-framework': '01. 한국사 시대 구분과 전 범위 구조 재정리',
  '02_question-types': '02. 독학사 국사 유형 지도: 개념·사료·비교·함정 선지',
  '03_core-concepts-method': '03. 4단계 국사에서 요구되는 사고 방식과 학습 전략',
  '04_prehistoric-early-states': '04. 선사와 국가 형성: 사회 구조와 국가의 탄생',
  '05_three-kingdoms-unification': '05. 삼국과 통일 신라·발해: 정치 구조와 대외관계',
  '06_land-tax-ancient': '06. 고대의 토지·조세·신분 제도 비교',
  '07_goryeo-politics-society': '07. 고려의 정치 체제와 사회 구조',
  '08_goryeo-economy-culture': '08. 고려의 경제와 불교 문화·사상',
  '09_joseon-early-system': '09. 조선 전기의 건국과 통치 체제',
  '10_land-tax-joseon': '10. 조선 전·후기의 토지·조세·신분 제도 종합 비교',
  '11_neo-confucianism-ideology': '11. 성리학·사림·조선 정치 사상',
  '12_late-joseon-reforms': '12. 조선 후기 경제 변화와 사회 개혁·실학',
  '13_opening-modern-state': '13. 개항기와 대한제국: 개혁과 근대 국가 시도',
  '14_colonial-rule': '14. 일제 강점기의 통치 체제와 식민지 경제',
  '15_independence-movements': '15. 독립운동의 전개: 국내외 무장·민족운동·사회운동',
  '16_division-modern-korea': '16. 해방·분단과 대한민국 현대사: 정치·경제·사회',
  '17_thematic-comparisons': '17. 시대 횡단 비교: 토지·신분·통치·개혁 종합 정리',
  '18_thought-religion-ideology': '18. 불교·성리학·실학·동학·근대 사상의 흐름',
  '19_source-reading': '19. 사료·문헌·도표 읽기: 독학사 국사 사료형 대비',
  '20_trap-options': '20. 보기 선지 함정 패턴과 오답 소거 기술',
  '21_integrated-mock': '21. 독학사 4단계 국사 통합 모의고사',
  '22_past-paper-analysis': '22. 회차별 기출 분석: 출제 경향과 난이도',
  '23_final-drill': '23. 독학사 4단계 국사 예상기출·최종 점검 문제',
}

export default meta
