const meta = {
  '01_data-analysis-problem-definition': '01. 분석 과제와 문제 정의',
  '02_analysis-planning-and-roadmap': '02. 분석 계획과 로드맵',
  '03_data-governance-and-quality': '03. 데이터 거버넌스와 품질',
  '04_privacy-security-and-ethics': '04. 개인정보, 보안과 분석 윤리',
  '05_analysis-methodology-and-project': '05. 분석 방법론과 프로젝트 관리',
  '06_performance-management': '06. KPI와 성과 관리',
  '07_big-data-platform-and-collection': '07. 빅데이터 플랫폼과 수집',
  '08_data-storage-and-processing': '08. 분산 저장과 처리',
  '09_data-preprocessing': '09. 데이터 전처리',
  '10_population-sample-and-data-types': '10. 모집단, 표본과 자료형',
  '11_descriptive-statistics': '11. 기술통계',
  '12_probability-and-distribution': '12. 확률과 확률분포',
  '13_hypothesis-testing': '13. 가설검정과 p값',
  '14_correlation-and-regression-basics': '14. 상관관계와 회귀 기초',
  '15_exploratory-analysis-and-visualization': '15. EDA와 시각화',
  '16_modeling-workflow-and-validation': '16. 모델링 절차와 검증',
  '17_linear-and-logistic-regression': '17. 선형회귀와 로지스틱 회귀',
  '18_decision-tree-and-ensemble': '18. 의사결정나무와 앙상블',
  '19_knn-naive-bayes-and-svm': '19. KNN, 나이브 베이즈와 SVM',
  '20_clustering': '20. 군집분석과 K-means',
  '21_association-and-recommendation': '21. 연관규칙과 추천',
  '22_dimension-reduction-and-feature-selection': '22. 차원 축소와 변수 선택',
  '23_model-evaluation-and-overfitting': '23. 모델 평가와 과적합',
  '24_optimization-and-model-selection': '24. 최적화와 모델 선택',
  '25_result-interpretation-and-communication': '25. 결과 해석과 커뮤니케이션',
  '26_visual-storytelling-and-deployment': '26. 시각화, 보고와 운영 적용',
  '27_planning-and-exploration-question-types': '27. 기획·탐색 기출 유형',
  '28_modeling-and-interpretation-question-types': '28. 모델링·결과 해석 기출 유형',
  '29_mock-exam-1': '29. 실전 모의 1회',
  '30_mock-exam-2': '30. 실전 모의 2회',
}

export default meta
