const meta = {
  '01_statistics-basics': '01. 통계 기초',
  '02_ml-basics': '02. 머신러닝 기초',
  '03_data-basics': '03. 데이터 기초',
  '04_data-analysis-problem-definition': '04. 분석 과제와 문제 정의',
  '05_analysis-planning-and-roadmap': '05. 분석 계획과 로드맵',
  '06_data-governance-and-quality': '06. 데이터 거버넌스와 품질',
  '07_privacy-security-and-ethics': '07. 개인정보, 보안과 분석 윤리',
  '08_analysis-methodology-and-project': '08. 분석 방법론과 프로젝트 관리',
  '09_performance-management': '09. KPI와 성과 관리',
  '10_big-data-platform-and-collection': '10. 빅데이터 플랫폼과 수집',
  '11_data-storage-and-processing': '11. 분산 저장과 처리',
  '12_data-preprocessing': '12. 데이터 전처리',
  '13_population-sample-and-data-types': '13. 모집단, 표본과 자료형',
  '14_descriptive-statistics': '14. 기술통계',
  '15_probability-and-distribution': '15. 확률과 확률분포',
  '16_hypothesis-testing': '16. 가설검정과 p값',
  '17_correlation-and-regression-basics': '17. 상관관계와 회귀 기초',
  '18_exploratory-analysis-and-visualization': '18. EDA와 시각화',
  '19_modeling-workflow-and-validation': '19. 모델링 절차와 검증',
  '20_linear-and-logistic-regression': '20. 선형회귀와 로지스틱 회귀',
  '21_decision-tree-and-ensemble': '21. 의사결정나무와 앙상블',
  '22_knn-naive-bayes-and-svm': '22. KNN, 나이브 베이즈와 SVM',
  '23_clustering': '23. 군집분석과 K-means',
  '24_association-and-recommendation': '24. 연관규칙과 추천',
  '25_dimension-reduction-and-feature-selection': '25. 차원 축소와 변수 선택',
  '26_model-evaluation-and-overfitting': '26. 모델 평가와 과적합',
  '27_optimization-and-model-selection': '27. 최적화와 모델 선택',
  '28_result-interpretation-and-communication': '28. 결과 해석과 커뮤니케이션',
  '29_visual-storytelling-and-deployment': '29. 시각화, 보고와 운영 적용',
  '30_planning-and-exploration-question-types': '30. 기획·탐색 기출 유형',
  '31_modeling-and-interpretation-question-types': '31. 모델링·결과 해석 기출 유형',
  '32_mock-exam-1': '32. 실전 모의 1회',
  '33_mock-exam-2': '33. 실전 모의 2회',
}

export default meta
