const meta = {
  '01_basic-math-stats': '01. 필기 대비를 위한 기초 수학·통계',
  '02_data-and-db-basics': '02. 데이터·데이터베이스·빅데이터 기초',
  '03_eda-visual-grammar': '03. 탐색적 데이터 분석과 시각화 문법',
  '04_ml-concepts-map': '04. 분류·회귀·군집 개념 지도',
  '05_planning-process': '05. 빅데이터 분석 기획: 분석 절차와 방법론',
  '06_bigdata-concepts': '06. 빅데이터의 이해와 데이터 거버넌스 기초',
  '07_data-collection-storage': '07. 데이터 수집·저장 계획',
  '08_planning-usecase': '08. 분석 과제 정의와 성과지표 설정',
  '09_data-preprocessing-1': '09. 데이터 전처리 I: 결측치와 이상치 처리',
  '10_data-preprocessing-2': '10. 데이터 전처리 II: 스케일링·인코딩·변환',
  '11_data-quality-eda': '11. 데이터 품질 진단과 탐색적 데이터 분석',
  '12_descriptive-stats': '12. 기술통계와 확률분포',
  '13_inference-hypothesis': '13. 추론통계와 가설검정',
  '14_correlation-regression-basics': '14. 상관·단순회귀·다중회귀 기초',
  '15_ml-modeling-design': '15. 분석 모형 설계: 문제 유형과 알고리즘 선택',
  '16_supervised-learning': '16. 지도학습: 주요 알고리즘과 개념',
  '17_unsupervised-learning': '17. 비지도학습·군집 분석',
  '18_model-evaluation-metrics-1': '18. 분류 모형 평가: 혼동행렬과 평가지표',
  '19_model-evaluation-metrics-2': '19. 회귀·군집 모형 평가와 과적합',
  '20_model-interpretation': '20. 분석 모형 해석과 적용',
  '21_visualization-communication': '21. 분석 결과 시각화와 스토리텔링',
  '22_bigdata-utilization': '22. 빅데이터 분석 결과 활용과 윤리',
  '23_past-questions-1': '23. 기출·복원 문항으로 보는 핵심 개념(최근 회차 1)',
  '24_past-questions-2': '24. 기출·복원 문항으로 보는 계산·평가지표(최근 회차 2)',
  '25_mock-exam-strategy': '25. 모의고사와 회차별 전략(과목당 40점·평균 60점 달성)',
  '26_mock-exam-1': '26. 빅데이터분석기사 필기 예상 모의고사 1회',
  '27_mock-exam-2': '27. 빅데이터분석기사 필기 예상 모의고사 2회',
  '28_mock-exam-3': '28. 빅데이터분석기사 필기 예상 모의고사 3회',
  '29_mock-exam-4': '29. 빅데이터분석기사 필기 예상 모의고사 4회',
  '30_mock-exam-5': '30. 빅데이터분석기사 필기 예상 모의고사 5회',
}

export default meta
