const meta = {
  '01_math-language': '01. 기호와 수학 문장 다시 잡기',
  '02_functions-basics': '02. 실수축과 함수 읽는 법',
  '03_sequences-basics': '03. 수열과 급수 입문',
  '04_trig-exp-log-basics': '04. 삼각·지수·로그함수 기초 개념',
  '05_sets-logic': '05. 집합과 명제: 기본 개념과 시험형 정리',
  '06_functions-types': '06. 함수의 종류와 그래프: 다항·유리·무리·지수·로그',
  '07_functions-equations-inequalities': '07. 함수와 방정식·부등식: 해석과 해 구하기',
  '08_sequences-formulas': '08. 등차·등비수열과 일반항, 합 공식 끝내기',
  '09_series-convergence': '09. 급수와 수렴 판별: 시험 수준 기법',
  '10_limit-of-sequences': '10. 수열의 극한과 연속: 기본 정의와 계산',
  '11_limit-of-functions': '11. 함수의 극한과 연속: 좌극한·우극한·불연속',
  '12_limit-techniques': '12. 극한 계산 기술: 유리화·인수분해·치환',
  '13_derivative-basics': '13. 미분의 정의와 기본 공식',
  '14_derivative-techniques': '14. 미분 계산 절차와 응용: 곡선의 성질',
  '15_integral-basics': '15. 적분의 개념과 부정·정적분',
  '16_integral-techniques': '16. 적분 계산 절차와 응용: 넓이·그래프',
  '17_matrix-basics': '17. 행렬의 정의와 연산',
  '18_determinant-vector': '18. 행렬식과 벡터 기초',
  '19_exam-overview-strategy': '19. 독학사 일반수학 시험 구조와 공략 전략',
  '20_calculation-drills': '20. 계산력 강화 세트: 단원별 연산 집중 연습',
  '21_mixed-practice-1': '21. 단원 통합 연습문제 1: 함수·수열·극한·미분',
  '22_mixed-practice-2': '22. 단원 통합 연습문제 2: 적분·행렬·벡터',
  '23_past-questions-set1': '23. 독학사 일반수학 기출 1: 기본 유형 분석',
  '24_past-questions-set2': '24. 독학사 일반수학 기출 2: 시간을 줄이는 풀이법',
  '25_mock-exam-1': '25. 독학사 일반수학 예상기출모의 1회',
  '26_mock-exam-2': '26. 독학사 일반수학 예상기출모의 2회',
}

export default meta
