const meta = {
  '01_numbers-and-real-line': '01. 수 체계와 수직선',
  '02_algebraic-expressions': '02. 대수 표현 — 변수, 전개, 인수분해',
  '03_coordinates-and-graphs': '03. 좌표계와 그래프 — 점, 직선, 포물선',
  '04_equations-and-inequalities': '04. 방정식과 부등식 — 일차·이차',
  '05_sets-and-operations': '05. 집합, 원소, 부분집합, 집합 연산',
  '06_functions': '06. 함수, 합성함수, 역함수',
  '07_matrix-basics': '07. 행렬의 뜻과 기본 연산',
  '08_matrix-multiplication': '08. 행렬 곱셈과 전치행렬',
  '09_inverse-matrix': '09. 역행렬과 연립방정식 풀이',
  '10_determinants': '10. 행렬식 — 2×2, 3×3, 역행렬 존재 조건',
  '11_vectors-and-operations': '11. 벡터, 크기, 덧셈·뺄셈·스칼라배',
  '12_dot-product': '12. 내적과 응용 — 각도, 직교',
  '13_lines-and-planes': '13. 직선과 평면의 방정식',
  '14_linear-programming': '14. 부등식과 선형계획 — 실수 범위 최적화',
  '15_limits': '15. 함수의 극한 — 수렴·발산, 극한 법칙',
  '16_continuity': '16. 연속의 정의와 불연속점 판별',
  '17_derivatives': '17. 미분계수와 기본 미분법',
  '18_differentiation-rules': '18. 합성함수 미분, 지수·로그·삼각 미분',
  '19_derivative-applications': '19. 증가·감소·오목볼록·극값 찾기',
  '20_optimization': '20. 최적화 문제와 선형근사',
  '21_indefinite-integrals': '21. 부정적분 — 역도함수, 기본 공식',
  '22_definite-integrals': '22. 정적분과 미적분학의 기본정리',
  '23_area-and-volume': '23. 정적분의 응용 — 면적과 부피',
  '24_substitution-integration': '24. 치환적분',
  '25_integration-by-parts': '25. 부분적분',
  '26_improper-integrals': '26. 이상적분 — 무한구간, 불연속점',
  '27_first-order-ode': '27. 일계 미분방정식 — 변수분리, 선형',
  '28_second-order-ode': '28. 이계 미분방정식 기초 — 상수계수 제차·비제차',
  '29_coordinate-systems': '29. 좌표계 — 직교, 극, 구면 좌표 변환',
  '30_partial-derivatives': '30. 편도함수와 전미분',
  '31_gradient-and-extrema': '31. 기울기 벡터, 극값 판별법',
}

export default meta
