const meta = {
  '01_math-basics': '01. 논리회로를 위한 최소 수학: 집합·명제·논리함수',
  '02_number-representation': '02. 진법 읽기 준비: 자리값·수 체계 개요',
  '03_boolean-notation': '03. 불 함수와 논리식 표기 관습',
  '04_digital-signal-concept': '04. 디지털 신호·비트·논리레벨 직관',
  '05_number-systems': '05. 수 체계와 진법 변환 (2·8·10·16진)',
  '06_codes-bcd-gray': '06. 코드 체계 I: BCD·그레이·여분3 코드',
  '07_complements-parity': '07. 코드 체계 II: 보수·패리티·부호화',
  '08_boolean-algebra-basics': '08. 불 대수 기초와 논리게이트',
  '09_standard-forms': '09. 표준형과 논리식 표현 (SOP/POS·극소항/극대항)',
  '10_karnaugh-map': '10. 카르노맵 I: 기본 원리와 2·3·4변수 간소화',
  '11_k-map-advanced': '11. 카르노맵 II: 무관항(don\'t care)·다중 출력·함정 패턴',
  '12_quine-mccluskey': '12. 퀴인-맥클러스키와 체계적 간소화',
  '13_combinational-basics': '13. 조합논리회로 개요와 설계 절차',
  '14_adders-subtractors': '14. 가산기·감산기와 산술 회로',
  '15_comparators-encoders': '15. 비교기·인코더·디코더·다중화기',
  '16_programmable-logic': '16. ROM·PLA·PAL과 프로그램 가능 논리',
  '17_latches-flipflops': '17. 래치·플립플롭(SR·D·JK·T)과 여기표',
  '18_flipflop-conversion-timing': '18. 플립플롭 변환·타이밍·레이스 조건',
  '19_sequential-design': '19. 순차회로 설계: 상태도·상태표·상태 방정식',
  '20_counters': '20. 카운터 설계: 동기·비동기·상태머신',
  '21_registers-shift': '21. 레지스터·시프트 레지스터',
  '22_memory-overview': '22. 기억장치 개요와 주소·용량 계산',
  '23_mock-previous': '23. 독학사 2단계 논리회로 예상·기출 문제 모음',
  '24_topic-drills-combinational': '24. 조합논리·카르노맵 집중 기출·유형 풀이',
  '25_topic-drills-sequential': '25. 플립플롭·카운터·순차회로 집중 기출·유형 풀이',
  '26_full-mock-exam': '26. 독학사 2단계 논리회로 실전 모의고사 (60분)',
}

export default meta
