const meta = {
  '01_math-basics': '01. 알고리즘 분석을 위한 수학·표기 기초',
  '02_asymptotic-notation': '02. 점근적 표기와 시간·공간 복잡도',
  '03_recurrence-basics': '03. 점화식과 재귀 알고리즘 분석 기초',
  '04_graph-modeling': '04. 그래프 모델링과 표현: 문제를 그래프로 옮기기',
  '05_basic-sorting': '05. 선택·삽입·버블 정렬: 기본 정렬과 복잡도 비교',
  '06_advanced-sorting': '06. 퀵·병합 정렬: 분할정복 정렬 알고리즘',
  '07_heap-sorting': '07. 힙 정렬과 힙 기반 선택 알고리즘',
  '08_non-comparison-sorting': '08. 기수 정렬과 계수 정렬: 비교 정렬 하한을 넘어서',
  '09_searching-hashing': '09. 순차·이진 탐색과 해시 탐색: 시간을 사는 대가 계산하기',
  '10_graph-traversal': '10. DFS와 BFS: 그래프 순회 알고리즘',
  '11_topology-mst': '11. 위상 정렬과 최소 신장 트리(MST)',
  '12_shortest-paths': '12. 최단경로 알고리즘: 다익스트라·벨만-포드·플로이드-워셜',
  '13_string-matching': '13. 문자열 패턴 매칭: 나이브와 KMP',
  '14_divide-and-conquer': '14. 분할정복 설계 기법과 대표 문제',
  '15_dynamic-vs-greedy': '15. 동적계획법과 탐욕 알고리즘: 언제 무엇을 쓰는가',
  '16_backtracking-branch-bound': '16. 백트래킹과 분기한정: 탐색 공간 줄이기',
  '17_complexity-theory': '17. 계산 복잡도 개요: P·NP·NP-완전·환원',
  '18_tricky-mixed-questions': '18. 혼합 알고리즘 문제 유형: 정렬·그래프·DP 결합',
  '19_prev-questions-sorting-search': '19. 예상·기출 변형: 정렬·탐색 파트',
  '20_prev-questions-graphs': '20. 예상·기출 변형: 그래프·최단경로·MST',
  '21_prev-questions-design': '21. 예상·기출 변형: 설계 기법(DP·탐욕·분할정복·백트래킹)',
  '22_prev-questions-complexity': '22. 예상·기출 변형: 계산 복잡도·NP-완전',
  '23_full-mock-exam': '23. 독학사 4단계 알고리즘 모의 종합시험 (실전 1회분)',
}

export default meta
