const meta = {
  '01_what-is-html-and-its-role': '01. HTML이란 무엇인가: 정의·어원·역할 분담',
  '02_anatomy-of-tags-and-attributes': '02. 태그·요소·속성의 문법 해부',
  '03_reading-mdn-and-whatwg': '03. MDN과 WHATWG 스펙 읽는 법',
  '04_document-skeleton-and-head': '04. 문서 뼈대와 head',
  '05_content-models-and-categories': '05. 콘텐츠 모델과 콘텐츠 카테고리',
  '06_text-semantics-basics': '06. 텍스트 시맨틱스 기본',
  '07_links-and-navigation': '07. 링크와 내비게이션',
  '08_images-basics': '08. 이미지의 전통적 기본기',
  '09_lists': '09. 리스트: 순서·비순서·설명 리스트',
  '10_tables-basics': '10. 표: 구조와 접근성 기초',
  '11_quotes-and-code-elements': '11. 인용과 코드 표시 요소',
  '12_global-attributes': '12. 전역 속성',
  '13_forms-structure-and-labels': '13. 폼의 구조와 레이블 연결',
  '14_forms-input-types-traditional': '14. 폼 입력의 전통적 타입',
  '15_forms-select-textarea-button': '15. select·textarea·button',
  '16_forms-submission-and-encoding': '16. 폼 제출과 데이터 인코딩',
  '17_semantic-sectioning-elements': '17. 시맨틱 sectioning 요소',
  '18_document-outline-reality': '18. 문서 아웃라인의 현실',
  '19_character-references-and-encoding': '19. 문자 참조와 인코딩 기초',
  '20_accessibility-basics': '20. 접근성 기초',
  '21_validation-and-common-mistakes': '21. 유효성 검사와 흔한 실수',
  '22_how-browsers-parse-html': '22. 브라우저는 HTML을 어떻게 파싱하는가',
  '23_building-a-semantic-page-exercise': '23. 종합 실습 1: 시맨틱 페이지와 폼 만들기',
  '24_debugging-invalid-html-exercise': '24. 종합 실습 2: 검증기로 오류 찾아 고치기',
  '25_comprehensive-review-and-checklist': '25. 종합 정리와 완료 기준 점검',
}

export default meta
