const meta = {
  '01_exam-overview': '01. 리눅스마스터 1급 1차 시험 구조와 출제 범위',
  '02_linux-architecture': '02. 리눅스 구조 한눈에 보기: 커널·사용자 공간·배포판',
  '03_boot-basics': '03. 부팅과 시스템 초기화 개요: BIOS/UEFI·커널·init/systemd',
  '04_shell-environment-basics': '04. 셸과 환경: 로그인 셸·환경변수·프로파일 개요',
  '05_permission-notation': '05. 권한 표기 읽는 법과 기본 파일시스템 개념',
  '06_linux-distributions-licenses': '06. 리눅스 실무의 이해 1: 배포판·패키지·라이선스',
  '07_kernel-and-user-space-deep': '07. 리눅스 실무의 이해 2: 커널·시스템 콜·사용자 공간',
  '08_filesystem-layout-mount': '08. 파일시스템 계층과 마운트: /, /home, /var, /etc',
  '09_process-concepts': '09. 프로세스의 이해: PID·PPID·포그라운드/백그라운드',
  '10_boot-runlevel-systemd-flow': '10. 부팅부터 로그인까지 깊게 보기: runlevel과 systemd target',
  '11_permissions-umask-acl-deep': '11. 권한·특수 비트·umask·ACL: 접근 제어의 실제 동작',
  '12_users-groups-auth': '12. 사용자·그룹 관리와 인증 기초',
  '13_disk-partition-lvm-quota': '13. 디스크·파티션·LVM·쿼터 개요',
  '14_service-management-sysv-systemd': '14. 서비스 관리: SysV 스크립트와 systemd 유닛 비교',
  '15_scheduling-cron-at': '15. 작업 스케줄링: cron과 at',
  '16_logging-monitoring-performance': '16. 로그·모니터링·기본 성능 관리',
  '17_backup-recovery-security-basics': '17. 백업·복구·보안 기초',
  '18_network-stack-osi-tcpip': '18. 네트워크 스택: OSI·TCP/IP와 리눅스 네트워크 계층',
  '19_network-config-routing-dns': '19. 인터페이스 설정·라우팅·DNS 해석 순서',
  '20_firewall-iptables-nftables-firewalld': '20. 방화벽 개념: iptables·nftables·firewalld',
  '21_ssh-concepts-config': '21. SSH 서비스: 원격 로그인·키 인증·설정 포인트',
  '22_http-ftp-services': '22. HTTP·FTP 서비스 개요와 설정 포인트',
  '23_nfs-samba-file-sharing': '23. NFS·Samba: 리눅스 파일 공유 서비스',
  '24_integrated-concepts-1': '24. 종합 정리 1: 부팅·프로세스·서비스·로그를 하나의 흐름으로',
  '25_integrated-concepts-2': '25. 종합 정리 2: 파일시스템·권한·백업·보안을 하나의 흐름으로',
  '26_integrated-concepts-3': '26. 종합 정리 3: 네트워크·방화벽·서비스 동작 흐름',
  '27_practice-linuxmaster-type-a': '27. 리눅스마스터 1급 1차 예상기출문제 A (리눅스 실무·시스템 관리)',
  '28_practice-linuxmaster-type-b': '28. 리눅스마스터 1급 1차 예상기출문제 B (네트워크·통합 시나리오)',
  '29_practice-linuxmaster-mixed-c': '29. 리눅스마스터 1급 1차 예상기출문제 C (혼합 난이도·함정 특화)',
  '30_practice-linuxmaster-diagnostic': '30. 진단 모의고사 1회분 (실전 시간·배점 구조 반영)',
  '31_practice-linuxmaster-review': '31. 기출 경향 리뷰와 오답 유형 분석',
}

export default meta
