const meta = {
  '01_adsp-exam-and-r-setup': '01. R과 RStudio 실습 환경 만들기',
  '02_data-information-knowledge-hierarchy': '02. 데이터·정보·지식·지혜 위계(DIKW)',
  '03_database-and-dbms-basics': '03. 데이터베이스와 DBMS의 특징',
  '04_bigdata-value-and-era-change': '04. 빅데이터의 가치와 산업 변화',
  '05_data-science-and-strategic-insight': '05. 데이터 사이언스와 전략적 인사이트',
  '06_analytics-planning-direction': '06. 데이터분석 기획의 방향',
  '07_analytics-methodology-crisp-dm-kdd': '07. 분석 방법론: CRISP-DM과 KDD',
  '08_analytics-task-discovery': '08. 분석 과제 발굴: 하향식과 상향식',
  '09_analytics-masterplan-and-roadmap': '09. 분석 마스터플랜과 우선순위 로드맵',
  '10_r-basic-syntax-and-data-types': '10. R 기초 문법과 데이터 타입',
  '11_r-data-structures-vector-to-dataframe': '11. R 데이터 구조: 벡터부터 데이터프레임까지',
  '12_r-data-handling-dplyr-basics': '12. R 데이터 전처리: dplyr 기초',
  '13_descriptive-statistics': '13. 기술통계: 중심경향과 산포',
  '14_probability-distributions': '14. 확률분포: 정규분포와 주요 분포',
  '15_sampling-and-estimation': '15. 표본추출과 추정',
  '16_hypothesis-testing': '16. 가설검정과 유의수준',
  '17_correlation-analysis': '17. 상관분석',
  '18_regression-analysis': '18. 회귀분석: 단순·다중 회귀',
  '19_time-series-analysis-basics': '19. 시계열분석 개요',
  '20_data-mining-overview-and-classification-map': '20. 데이터마이닝 개관과 분류 기법 지도',
  '21_decision-tree': '21. 분류 1: 의사결정나무',
  '22_logistic-regression-and-ensemble': '22. 분류 2: 로지스틱 회귀와 앙상블',
  '23_clustering-analysis': '23. 군집분석: K-means와 계층적 군집',
  '24_association-rules': '24. 연관규칙분석',
  '25_model-evaluation-metrics': '25. 모형평가: 혼동행렬과 평가지표',
  '26_mock-exam-1': '26. ADsP 예상 모의고사 1회',
  '27_mock-exam-2': '27. ADsP 예상 모의고사 2회',
  '28_mock-exam-3': '28. ADsP 예상 모의고사 3회',
  '29_mock-exam-4': '29. ADsP 예상 모의고사 4회',
  '30_mock-exam-5': '30. ADsP 예상 모의고사 5회',
}

export default meta
