const meta = {
  '01_web-platform-basics': '01. 브라우저 Web 플랫폼 지도: JS 엔진·DOM·Web API 경계',
  '02_api-design-patterns': '02. Web API 설계 패턴 읽는 법: 인터페이스·IDL·스펙 용어',
  '03_rendering-pipeline': '03. 브라우저 렌더링 파이프라인: 파싱부터 페인트까지',
  '04_http-rest-basics': '04. HTTP와 REST 기초: 네트워크 API를 읽는 토대',
  '05_dom-model-advanced': '05. 문서 모델 심화: DOM, Range, Selection, CSSOM',
  '06_event-system-deep-dive': '06. 이벤트 시스템 기본기: 캡처·버블·위임·커스텀 이벤트',
  '07_abort-signal-and-cancellation': '07. AbortSignal로 비동기 취소 모델 이해하기',
  '08_navigation-and-history': '08. 내비게이션·히스토리·URL·URLPattern',
  '09_dom-events-in-depth': '09. 고급 이벤트 주제: 수동 디스패치, 이벤트 옵션, 입력 이벤트',
  '10_fetch-anatomy': '10. Fetch 심층 해부: Request/Response/Headers, CORS, 취소',
  '11_streaming-with-fetch': '11. WHATWG Streams와 Fetch 본문 소비 규칙',
  '12_realtime-networking': '12. 실시간 네트워킹: WebSocket과 Server-Sent Events',
  '13_storage-overview': '13. 브라우저 저장소 지도: Cookie, Web Storage, origin·quota',
  '14_cache-storage-and-http-cache': '14. Cache Storage와 HTTP 캐시의 API 계약',
  '15_indexeddb-basics': '15. IndexedDB 입문: 데이터 모델과 비동기 트랜잭션',
  '16_indexeddb-design-patterns': '16. IndexedDB로 설계하는 저장소: 패턴과 한계',
  '17_observers-intro': '17. 관측자 패밀리: Mutation, Intersection, Resize, Performance',
  '18_timing-and-page-lifecycle': '18. 타이머·rAF·Page Lifecycle: 실행 시점 제어',
  '19_workers-intro': '19. Worker·SharedWorker: 메인 스레드를 비우는 기본기',
  '20_service-worker-api-contract': '20. Service Worker와 캐시 전략의 API 계약',
  '21_file-and-binary': '21. 파일·바이너리: Blob, File, FileReader, 객체 URL, Encoding',
  '22_web-components-deep-dive': '22. Web Components: Custom Elements·Shadow DOM·템플릿',
  '23_main-thread-offloading-patterns': '23. Observer·rAF·워커를 결합한 메인 스레드 비우기 패턴',
  '24_permissions-and-security-surfaces': '24. 권한·보안 표면: Permissions API, 안전한 컨텍스트, origin 격리',
  '25_web-crypto-overview': '25. Web Crypto crypto.subtle 개요와 안전한 사용',
  '26_browser-integration-apis': '26. 미디어·클립보드·드래그앤드롭·Fullscreen 등 브라우저 통합',
  '27_web-apis-design-exercises-1': '27. 설계·조합 연습 1: 네트워크·저장소 중심',
  '28_web-apis-design-exercises-2': '28. 설계·조합 연습 2: 관측·타이밍·워커 중심',
  '29_web-apis-design-exercises-3': '29. 설계·조합 연습 3: Web Components·보안 중심',
  '30_appendix-when-to-leave-this-course': '30. 부록: WebGL·WebRTC·WebAssembly 등 특화 API로 넘어가는 시점',
}

export default meta
