const meta = {
  '01_language-basics-bridging': '01. C·Java 기초 문법 빠른 복습과 독학사 스타일 문항 맛보기',
  '02_oop-terminology-map': '02. 객체지향 용어 지도: 클래스·객체·상속·다형성 개념 정리',
  '03_data-structures-concepts': '03. 자료구조·알고리즘 개념 지도: 리스트·스택·큐·트리·그래프·복잡도',
  '04_web-db-network-overview': '04. 웹·DB·네트워크 프로그래밍 큰 그림: 계층·역할·연동 흐름',
  '05_c-core-1': '05. C 언어 핵심 ①: 배열·문자열·포인터 기초와 주소·참조 추적',
  '06_c-core-2': '06. C 언어 핵심 ②: 포인터와 함수, 동적 메모리 할당',
  '07_c-struct-fileio': '07. C 구조체와 파일 I/O: 레코드 처리·구현 패턴',
  '08_java-basics-1': '08. Java 기초 ①: 클래스와 객체, 생성자, 기본 문법 정리',
  '09_java-oop-1': '09. Java 객체지향 ①: 상속·오버라이딩·다형성과 실행 결과 추적',
  '10_java-oop-2': '10. Java 객체지향 ②: 추상 클래스·인터페이스·캡슐화와 설계 문제',
  '11_java-exception-collection': '11. Java 예외 처리와 컬렉션 프레임워크',
  '12_data-structures-impl-1': '12. 자료구조 구현 ①: 배열·리스트·스택·큐와 재귀',
  '13_data-structures-impl-2': '13. 자료구조 구현 ②: 트리·그래프와 탐색 알고리즘',
  '14_sort-search-complexity': '14. 정렬·탐색 알고리즘과 시간복잡도 기초',
  '15_gui-event': '15. GUI 프로그래밍과 이벤트 처리 기초',
  '16_db-sql-review': '16. 데이터베이스·SQL 복습: 통합프로그래밍 관점에서 보는 DB',
  '17_java-jdbc': '17. Java와 JDBC: DB 연동 코드 구조와 예외 처리',
  '18_web-front-basic': '18. 웹 프로그래밍 ①: HTML·CSS·JavaScript 기초와 폼 처리',
  '19_web-jsp-servlet': '19. 웹 프로그래밍 ②: JSP·Servlet과 MVC 구조',
  '20_network-socket': '20. 네트워크 프로그래밍 기초: 소켓·프로토콜·간단 통신 코드',
  '21_integrated-practice-1': '21. 통합 실습 ①: C·자료구조·알고리즘 연계 손코딩',
  '22_integrated-practice-2': '22. 통합 실습 ②: Java·웹·DB·네트워크 연계 손코딩',
  '23_past-questions-style': '23. 기출 분석 ①: 평가영역·문항 유형·난이도 흐름 읽기',
  '24_past-questions-c-java': '24. 기출·모의 ②: C·Java 핵심 문법·실행 결과·오류 찾기',
  '25_past-questions-web-db-network': '25. 기출·모의 ③: 웹·DB·네트워크·자료구조 연동 문제',
}

export default meta
