const meta = {
  '01_programming-language-vs-implementation': '01. 프로그래밍언어 개념 지도: 언어·구현·패러다임',
  '02_syntax-notation-and-grammar-basics': '02. 구문 표기법 기초: BNF/EBNF와 구문 도표 읽기',
  '03_names-types-binding-vocabulary': '03. 이름·형·바인딩·스코프 용어 지도',
  '04_control-and-subprogram-concepts': '04. 제어 구조와 하위프로그램 개념 지도',
  '05_concurrency-and-exception-vocabulary': '05. 병행성·예외 처리 개념 지도',
  '06_evolution-and-paradigms-of-pl': '06. 프로그래밍언어의 역사와 패러다임',
  '07_language-evaluation-and-design': '07. 언어 평가 기준과 설계 원칙',
  '08_describing-syntax-and-semantics': '08. 구문과 의미: BNF/EBNF·속성 문법·정적/동적 의미',
  '09_names-bindings-scope-lifetime': '09. 이름·바인딩·스코프·수명 심화',
  '10_type-systems-and-type-checking': '10. 자료형과 형 시스템: 강/약, 정적/동적, 형 검사',
  '11_data-types-and-pointers-references': '11. 배열·레코드·포인터·참조 등 자료형 설계',
  '12_expressions-assignment-short-circuit': '12. 식·연산자·할당·단락 평가',
  '13_statement-level-control-structures': '13. 제어 구조 설계와 비교',
  '14_subprogram-concepts-and-parameter-passing': '14. 하위프로그램 개념과 매개변수 전달 방식',
  '15_implementing-subprograms-activation-records': '15. 하위프로그램 구현: 활성화 레코드·정적/동적 체인',
  '16_overloading-generic-subprograms': '16. 오버로딩·제네릭 하위프로그램과 모듈화',
  '17_abstract-data-types-and-encapsulation': '17. 추상 자료형과 캡슐화',
  '18_object-oriented-support': '18. 객체지향 언어 지원: 클래스·상속·다형성·동적 바인딩',
  '19_concurrency-semaphores-monitors-message': '19. 병행성 지원: 세마포어·모니터·메시지 전달',
  '20_exception-handling-and-event-handling': '20. 예외 처리와 이벤트 처리',
  '21_language-implementations-and-runtime': '21. 언어 구현 방식과 런타임 환경 개요',
  '22_functional-programming-overview': '22. 함수형 언어 개요: 람다·순수 함수·고차 함수',
  '23_logic-programming-and-prolog-overview': '23. 논리형 언어 개요: Horn 절·Prolog',
  '24_exam-type-concept-questions-1': '24. 개념·정의형 예상문제 1 (언어 평가·구문·의미)',
  '25_exam-type-concept-questions-2': '25. 개념·정의형 예상문제 2 (이름·형·스코프·자료형)',
  '26_exam-type-code-and-model-questions': '26. 코드·모델 추론형 예상문제 (제어·하위프로그램·활성화 레코드)',
  '27_past-exams-analysis-1': '27. 독학사 프로그래밍언어론 기출 분석 1 (개념·정의 중심)',
  '28_past-exams-analysis-2': '28. 독학사 프로그래밍언어론 기출 분석 2 (코드·모델 중심)',
}

export default meta
