const meta = {
  '01_math-basics': '01. 논리회로를 위한 최소 수학: 집합·명제·논리함수',
  '02_number-representation': '02. 진법 읽기 준비: 자리값·수 체계 개요',
  '03_boolean-notation': '03. 불 함수와 논리식 표기 관습',
  '04_digital-signal-concept': '04. 디지털 신호·비트·논리레벨 직관',
  '05_exam-format': '05. 독학사 2단계 논리회로 시험 구조와 학습 전략',
  '06_number-systems': '06. 수 체계와 진법 변환 (2·8·10·16진)',
  '07_codes-bcd-gray': '07. 코드 체계 I: BCD·그레이·여분3 코드',
  '08_complements-parity': '08. 코드 체계 II: 보수·패리티·부호화',
  '09_boolean-algebra-basics': '09. 불 대수 기초와 논리게이트',
  '10_standard-forms': '10. 표준형과 논리식 표현 (SOP/POS·극소항/극대항)',
  '11_karnaugh-map': '11. 카르노맵 I: 기본 원리와 2·3·4변수 간소화',
  '12_k-map-advanced': '12. 카르노맵 II: 무관항(don’t care)·다중 출력·함정 패턴',
  '13_quine-mccluskey': '13. 퀴인-맥클러스키와 체계적 간소화',
  '14_combinational-basics': '14. 조합논리회로 개요와 설계 절차',
  '15_adders-subtractors': '15. 가산기·감산기와 산술 회로',
  '16_comparators-encoders': '16. 비교기·인코더·디코더·다중화기',
  '17_programmable-logic': '17. ROM·PLA·PAL과 프로그램 가능 논리',
  '18_latches-flipflops': '18. 래치·플립플롭(SR·D·JK·T)과 여기표',
  '19_flipflop-conversion-timing': '19. 플립플롭 변환·타이밍·레이스 조건',
  '20_sequential-design': '20. 순차회로 설계: 상태도·상태표·상태 방정식',
  '21_counters': '21. 카운터 설계: 동기·비동기·상태머신',
  '22_registers-shift': '22. 레지스터·시프트 레지스터',
  '23_memory-overview': '23. 기억장치 개요와 주소·용량 계산',
  '24_mock-previous': '24. 독학사 2단계 논리회로 예상·기출 문제 모음',
  '25_topic-drills-combinational': '25. 조합논리·카르노맵 집중 기출·유형 풀이',
  '26_topic-drills-sequential': '26. 플립플롭·카운터·순차회로 집중 기출·유형 풀이',
  '27_full-mock-exam': '27. 독학사 2단계 논리회로 실전 모의고사 (60분)',
}

export default meta
