const meta = {
  '01_ecmascript-overview': '01. ECMAScript를 읽는 법: 표준, 용어, 버전',
  '02_js-runtime-map': '02. JavaScript 런타임 지도: 엔진, 호스트, 이벤트 루프 맛보기',
  '03_values-types-mental-model': '03. 값과 타입의 정신 모델: 원시값, 객체, 참조, 동일성',
  '04_syntax-and-strict-mode': '04. strict mode와 script/module, 안전한 기본 규칙',
  '05_coercion-and-abstract-operations': '05. 타입 강제 변환의 내부: ToPrimitive, ToNumber, ToBoolean',
  '06_operators-and-short-circuit': '06. 연산자 심층: 비교, 논리, 단축 평가, 옵셔널 체이닝',
  '07_objects-and-property-attributes': '07. 객체의 내부: 프로퍼티 어트리뷰트, getter/setter, 복사',
  '08_functions-first-class': '08. 함수의 본질: 일급 함수, 정의 방식, 화살표 함수',
  '09_execution-context-and-scope': '09. 실행 컨텍스트와 스코프 체인: 호이스팅, 렉시컬 환경, TDZ',
  '10_closure-and-lifetime': '10. 클로저와 생존 시간: 캡처, 은닉, 의도치 않은 공유',
  '11_constructor-and-object-creation': '11. 생성자 함수와 객체 생성: new의 내부 동작',
  '12_this-binding': '12. this 바인딩: 호출 방식이 전부다',
  '13_prototype-chain': '13. 프로토타입: 연결로 만드는 상속',
  '14_class-deep-dive': '14. class 딥 다이브: 필드, private, static, extends',
  '15_built-in-objects-and-wrappers': '15. 빌트인 객체와 래퍼 객체: 원시값에 메서드가 있는 이유',
  '16_symbol': '16. 심볼: 충돌 없는 키와 웰노운 심볼',
  '17_array-deep-dive-1': '17. 배열 1: 생성, 희소 배열, 요소 조작',
  '18_array-deep-dive-2': '18. 배열 2: 고차 함수로 데이터 다루기',
  '19_number-math-date': '19. Number, Math, Date: 숫자와 시간의 함정',
  '20_string-methods': '20. String: 문자열 메서드와 유니코드',
  '21_regexp': '21. 정규표현식: 패턴으로 문자열 다루기',
  '22_spread-destructuring': '22. 스프레드와 디스트럭처링: 펼치고 뽑아내기',
  '23_set-map': '23. Set과 Map: 객체·배열이 아닌 자료구조',
  '24_iterables-generators': '24. 반복 프로토콜: 이터러블, 이터레이터, 제너레이터',
  '25_promises': '25. Promise: 상태 기계로 이해하는 비동기',
  '26_async-await': '26. async/await: 동기처럼 쓰는 비동기',
  '27_event-loop-queues': '27. 이벤트 루프와 잡 큐: 실행 순서의 진실',
  '28_error-handling': '28. 에러 처리: throw, try/catch, 커스텀 에러 설계',
  '29_modules-esm': '29. ES 모듈: import/export, live binding, 순환 의존',
  '30_memory-gc-overview': '30. 메모리와 GC 개요: 도달 가능성과 누수 감각',
  '31_latest-ecmascript-syntax': '31. 최신 ECMAScript 읽기: 새 문법을 모델에 붙이기',
  '32_experiments-coercion-scope': '32. 실험 1: 변환·스코프·호이스팅 재현 문제',
  '33_experiments-this-prototype-class': '33. 실험 2: this·프로토타입·class 디버깅 문제',
  '34_experiments-async-eventloop': '34. 실험 3: Promise·async/await·이벤트 루프 출력 순서',
  '35_comprehensive-practice': '35. 종합 진단: JavaScript Deep Dive 예상문제',
}

export default meta
