const meta = {
  '01_reading-chord-scale-notation': '01. 코드-스케일 이론 표기 읽는 법',
  '02_reading-polychord-and-slash-chord-notation': '02. 폴리코드·분수코드 표기 읽는 법',
  '03_reading-arrangement-structure-terms': '03. 편곡 구조 용어 읽는 법',
  '04_upper-structure-triads': '04. 어퍼 스트럭처 트라이어드: 원리와 적용',
  '05_quartal-voicing-basics': '05. 쿼털 보이싱 기초: 4도 쌓기와 소리 특성',
  '06_quartal-voicing-modal-application': '06. 쿼털 보이싱 응용: 모달 반주에서 쓰기',
  '07_reharmonization-1-tritone-substitution': '07. 리하모니제이션 1: 대리 코드와 트라이톤 대리',
  '08_reharmonization-2-line-cliche-chromatic-bass': '08. 리하모니제이션 2: 라인 클리셰와 반음계 베이스',
  '09_reharmonization-3-constant-structure-parallel-motion': '09. 리하모니제이션 3: 정속 구조와 평행 이동',
  '10_modal-jazz-theory-dorian-lydian': '10. 모달 재즈 이론: 도리안·리디안 사운드와 코드-스케일',
  '11_modal-jazz-performance-pedal-point': '11. 모달 재즈 연주: 페달 포인트와 보이싱 움직임',
  '12_bebop-scales-five-types': '12. 비밥 스케일 5종과 사용법',
  '13_bebop-phrasing-enclosures-chromatic-approach': '13. 비밥 프레이징: 인클로저와 크로매틱 접근음',
  '14_bebop-line-construction-chord-tones': '14. 비밥 라인 만들기: 코드톤 중심 8분음표 라인',
  '15_transcription-methodology': '15. 트랜스크립션 방법론: 듣고 채보하는 절차',
  '16_transcription-practice-short-phrase': '16. 트랜스크립션 실습: 짧은 프레이즈 채보하고 적용하기',
  '17_solo-piano-arranging-1-walking-plus-voicing': '17. 솔로 피아노 어레인지 1: 왼손 워킹+오른손 보이싱 동시 연주',
  '18_solo-piano-arranging-2-stride-elements': '18. 솔로 피아노 어레인지 2: 스트라이드 요소 가미',
  '19_solo-piano-arranging-3-intro-and-ending': '19. 솔로 피아노 어레인지 3: 인트로·엔딩(태그) 만들기',
  '20_trio-performance-1-voicing-space-with-bassist': '20. 트리오 연주 실무 1: 베이시스트와 보이싱 공간 나누기',
  '21_trio-performance-2-comping-signals-dynamics': '21. 트리오 연주 실무 2: 컴핑 신호와 다이내믹 주고받기',
  '22_trio-performance-3-trading-fours': '22. 트리오 연주 실무 3: 트레이딩 포즈와 솔로 구성',
  '23_synthesis-reharmonized-standard-trio-plan': '23. 종합: 스탠다드 리하모니제이션 편곡 후 트리오 연주 계획 세우기',
  '24_song-project-1-reharmonized-solo-piano-arrangement': '24. 곡 프로젝트 1: 오리지널 진행 리하모니제이션+솔로 피아노 편곡',
  '25_song-project-2-original-modal-tune-trio': '25. 곡 프로젝트 2: 오리지널 모달 곡 작곡과 트리오 연주안 작성',
  '26_self-check-checklist-and-roadmap': '26. 자가 점검 체크리스트: 재즈피아노 3단계 총정리와 이후 로드맵',
}

export default meta
