const meta = {
  '01_transmission-math-basics': '01. 통신 계산을 위한 수학 기초',
  '02_digital-logic-reading': '02. 디지털 논리 회로 읽는 법',
  '03_communication-system-big-picture': '03. 통신 시스템의 큰 그림과 용어 지도',
  '04_computer-architecture-os-term-map': '04. 컴퓨터 구조와 운영체제 최소 용어 지도',
  '05_network-internet-term-map': '05. 네트워크와 인터넷 최소 용어 지도',
  '06_source-coding-pulse-modulation-and-line-codes': '06. 원천부호화·펄스변조와 라인코드',
  '07_analog-digital-modulation': '07. 아날로그·디지털 변복조',
  '08_oscillator-filter-and-logic-circuits': '08. 통신 회로 기초: 발진회로·필터·논리회로',
  '09_wired-media-propagation-and-line-facilities': '09. 유선 전송매체와 전파의 특성, 통신선로 시설·측정',
  '10_signal-quality-analysis-and-transmission-metrics': '10. 신호 품질 분석과 전송 성능 지표',
  '11_multiplexing-multiple-access-and-wideband-transmission': '11. 다중화·다중접속 기술과 광대역 전송',
  '12_terminal-equipment-and-transmission-facilities': '12. 단말기기의 기능·종류와 통신장비·전송설비',
  '13_line-service-and-mobile-terminal-devices': '13. 회선개통과 이동통신·인입선 단말 서비스',
  '14_video-processing-home-network-and-switching-equipment': '14. 영상정보처리·홈네트워크 설비와 교환기기',
  '15_network-design-basics-and-reference-model': '15. 네트워크 설계 기초와 참조모델',
  '16_internet-addressing-and-protocol-practice': '16. 인터넷 주소체계와 프로토콜 실무',
  '17_lan-design-switching-and-vlan': '17. LAN 설계와 스위칭·VLAN',
  '18_routing-redundancy-and-transport-network': '18. 라우팅·이중화와 구내교환·전송망 기술',
  '19_mobile-satellite-and-home-network-services': '19. 이동통신망·위성통신망과 홈네트워크 서비스',
  '20_server-construction-and-storage': '20. 서버 구축과 스토리지',
  '21_server-virtualization-and-cloud-computing': '21. 서버 가상화와 클라우드 컴퓨팅',
  '22_broadcast-reception-and-cabling-facilities': '22. 방송공동수신·통합배선 설비와 운용계획',
  '23_premises-facilities-and-network-security-management': '23. 구내통신 설비와 네트워크 보안관리',
  '24_computer-hardware-os-network-and-security-overview': '24. 컴퓨터 하드웨어·운영체제와 네트워크·보안 일반, 빅데이터 개요',
  '25_telecom-law-basic-and-business-act': '25. 정보통신 관련 법규 Ⅰ: 전기통신기본법·전기통신사업법·방송통신발전기본법',
  '26_telecom-construction-act-and-technical-standards': '26. 정보통신 관련 법규 Ⅱ: 정보통신공사업법과 방송통신설비 기술기준',
  '27_video-surveillance-law-and-design-supervision': '27. 지능형 영상관제 법령과 설계·감리 업무',
  '28_past-questions-transmission-and-equipment': '28. 기출·복원 유형으로 보는 정보전송일반·정보통신기기 핵심 함정',
  '29_past-questions-network-and-operations': '29. 기출·복원 유형으로 보는 정보통신네트워크·정보시스템운용 핵심 함정',
  '30_past-questions-computer-general-and-law': '30. 기출·복원 유형으로 보는 컴퓨터일반 및 법규 핵심 함정과 계산 문제',
  '31_mock-exam-1': '31. 정보통신기사 필기 예상 모의고사 1회',
  '32_mock-exam-2': '32. 정보통신기사 필기 예상 모의고사 2회',
}

export default meta
